// This file is part of the SORA network and Polkaswap app.

// Copyright (c) 2020, 2021, Polka Biome Ltd. All rights reserved.
// SPDX-License-Identifier: BSD-4-Clause

// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:

// Redistributions of source code must retain the above copyright notice, this list
// of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice, this
// list of conditions and the following disclaimer in the documentation and/or other
// materials provided with the distribution.
//
// All advertising materials mentioning features or use of this software must display
// the following acknowledgement: This product includes software developed by Polka Biome
// Ltd., SORA, and Polkaswap.
//
// Neither the name of the Polka Biome Ltd. nor the names of its contributors may be used
// to endorse or promote products derived from this software without specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY Polka Biome Ltd. AS IS AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Polka Biome Ltd. BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
// USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

//! Autogenerated weights for eth_bridge
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-07-19, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `takemiyamakotonoMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// /Users/takemiyamakoto/dev/sora2-network/target/release/framenode
// benchmark
// pallet
// --runtime=/Users/takemiyamakoto/dev/sora2-network/target/release/wbuild/framenode-runtime/framenode_runtime.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=benchmark
// --steps=50
// --repeat=20
// --pallet=eth_bridge
// --extrinsic=*
// --wasm-execution=compiled
// --header=/Users/takemiyamakoto/dev/sora2-network/misc/file_header.txt
// --output=/Users/takemiyamakoto/dev/sora2-network/pallets/eth-bridge/src/weights.rs
// --template=/Users/takemiyamakoto/dev/sora2-network/misc/pallet-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for eth_bridge.
#[allow(dead_code)]
pub trait WeightInfo {
	fn transfer_to_sidechain() -> Weight;
	fn request_from_sidechain() -> Weight;
	fn register_incoming_request() -> Weight;
	fn finalize_incoming_request() -> Weight;
	fn approve_request() -> Weight;
	fn approve_request_finalize() -> Weight;
	fn abort_request() -> Weight;
}

/// Weights for eth_bridge using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissioned` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissioned` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::DeprecatedSidechainTokens` (r:1 w:0)
	/// Proof: `EthBridge::DeprecatedSidechainTokens` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LockedAssets` (r:1 w:1)
	/// Proof: `BridgeProxy::LockedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LimitedAssets` (r:1 w:0)
	/// Proof: `BridgeProxy::LimitedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Senders` (r:0 w:1)
	/// Proof: `BridgeProxy::Senders` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Transactions` (r:0 w:1)
	/// Proof: `BridgeProxy::Transactions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn transfer_to_sidechain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140672`
		//  Estimated: `325556`
		// Minimum execution time: 768_000_000 picoseconds.
		Weight::from_parts(831_000_000, 325556)
			.saturating_add(T::DbWeight::get().reads(17_u64))
			.saturating_add(T::DbWeight::get().writes(12_u64))
	}
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:2 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:2 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissionedAt` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissionedAt` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissioned` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissioned` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:1 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request_from_sidechain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140175`
		//  Estimated: `146115`
		// Minimum execution time: 669_000_000 picoseconds.
		Weight::from_parts(712_000_000, 146115)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LoadToIncomingRequestHash` (r:1 w:1)
	/// Proof: `EthBridge::LoadToIncomingRequestHash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissioned` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissioned` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LockedAssets` (r:1 w:1)
	/// Proof: `BridgeProxy::LockedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:0 w:2)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_incoming_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140098`
		//  Estimated: `143563`
		// Minimum execution time: 0_000 picoseconds.
		Weight::from_parts(1_060_000_000, 143563)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissioned` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissioned` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Senders` (r:0 w:1)
	/// Proof: `BridgeProxy::Senders` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Transactions` (r:0 w:1)
	/// Proof: `BridgeProxy::Transactions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn finalize_incoming_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `67154`
		//  Estimated: `325556`
		// Minimum execution time: 425_000_000 picoseconds.
		Weight::from_parts(456_000_000, 325556)
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `EthBridge::Peers` (r:1 w:0)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:0)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissionedAt` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissionedAt` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissioned` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissioned` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:1 w:0)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeContractAddress` (r:1 w:0)
	/// Proof: `EthBridge::BridgeContractAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PendingPeer` (r:1 w:0)
	/// Proof: `EthBridge::PendingPeer` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn approve_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `14003`
		//  Estimated: `17468`
		// Minimum execution time: 264_000_000 picoseconds.
		Weight::from_parts(284_000_000, 17468)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `EthBridge::Peers` (r:1 w:0)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissionedAt` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissionedAt` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissioned` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissioned` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:1 w:0)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeContractAddress` (r:1 w:0)
	/// Proof: `EthBridge::BridgeContractAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PendingPeer` (r:1 w:0)
	/// Proof: `EthBridge::PendingPeer` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:1 w:1)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `BridgeProxy::Senders` (r:1 w:0)
	/// Proof: `BridgeProxy::Senders` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Transactions` (r:1 w:1)
	/// Proof: `BridgeProxy::Transactions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn approve_request_finalize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `77325`
		//  Estimated: `80790`
		// Minimum execution time: 602_000_000 picoseconds.
		Weight::from_parts(659_000_000, 80790)
			.saturating_add(T::DbWeight::get().reads(18_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LockedAssets` (r:1 w:1)
	/// Proof: `BridgeProxy::LockedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn abort_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `67149`
		//  Estimated: `325556`
		// Minimum execution time: 368_000_000 picoseconds.
		Weight::from_parts(395_000_000, 325556)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissioned` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissioned` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::DeprecatedSidechainTokens` (r:1 w:0)
	/// Proof: `EthBridge::DeprecatedSidechainTokens` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LockedAssets` (r:1 w:1)
	/// Proof: `BridgeProxy::LockedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LimitedAssets` (r:1 w:0)
	/// Proof: `BridgeProxy::LimitedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Senders` (r:0 w:1)
	/// Proof: `BridgeProxy::Senders` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Transactions` (r:0 w:1)
	/// Proof: `BridgeProxy::Transactions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn transfer_to_sidechain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140672`
		//  Estimated: `325556`
		// Minimum execution time: 768_000_000 picoseconds.
		Weight::from_parts(831_000_000, 325556)
			.saturating_add(RocksDbWeight::get().reads(17_u64))
			.saturating_add(RocksDbWeight::get().writes(12_u64))
	}
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:2 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:2 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissionedAt` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissionedAt` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissioned` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissioned` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:1 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request_from_sidechain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140175`
		//  Estimated: `146115`
		// Minimum execution time: 669_000_000 picoseconds.
		Weight::from_parts(712_000_000, 146115)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LoadToIncomingRequestHash` (r:1 w:1)
	/// Proof: `EthBridge::LoadToIncomingRequestHash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissioned` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissioned` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LockedAssets` (r:1 w:1)
	/// Proof: `BridgeProxy::LockedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:0 w:2)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_incoming_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140098`
		//  Estimated: `143563`
		// Minimum execution time: 0_000 picoseconds.
		Weight::from_parts(1_060_000_000, 143563)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissioned` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissioned` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Senders` (r:0 w:1)
	/// Proof: `BridgeProxy::Senders` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Transactions` (r:0 w:1)
	/// Proof: `BridgeProxy::Transactions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn finalize_incoming_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `67154`
		//  Estimated: `325556`
		// Minimum execution time: 425_000_000 picoseconds.
		Weight::from_parts(456_000_000, 325556)
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `EthBridge::Peers` (r:1 w:0)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:0)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissionedAt` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissionedAt` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissioned` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissioned` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:1 w:0)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeContractAddress` (r:1 w:0)
	/// Proof: `EthBridge::BridgeContractAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PendingPeer` (r:1 w:0)
	/// Proof: `EthBridge::PendingPeer` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn approve_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `14003`
		//  Estimated: `17468`
		// Minimum execution time: 264_000_000 picoseconds.
		Weight::from_parts(284_000_000, 17468)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `EthBridge::Peers` (r:1 w:0)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissionedAt` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissionedAt` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LegacyEthereumXorDecommissioned` (r:1 w:0)
	/// Proof: `EthBridge::LegacyEthereumXorDecommissioned` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:1 w:0)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeContractAddress` (r:1 w:0)
	/// Proof: `EthBridge::BridgeContractAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PendingPeer` (r:1 w:0)
	/// Proof: `EthBridge::PendingPeer` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:1 w:1)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `BridgeProxy::Senders` (r:1 w:0)
	/// Proof: `BridgeProxy::Senders` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Transactions` (r:1 w:1)
	/// Proof: `BridgeProxy::Transactions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn approve_request_finalize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `77325`
		//  Estimated: `80790`
		// Minimum execution time: 602_000_000 picoseconds.
		Weight::from_parts(659_000_000, 80790)
			.saturating_add(RocksDbWeight::get().reads(18_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LockedAssets` (r:1 w:1)
	/// Proof: `BridgeProxy::LockedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn abort_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `67149`
		//  Estimated: `325556`
		// Minimum execution time: 368_000_000 picoseconds.
		Weight::from_parts(395_000_000, 325556)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
}
