// This file is part of the SORA network and Polkaswap app.

// Copyright (c) 2020, 2021, Polka Biome Ltd. All rights reserved.
// SPDX-License-Identifier: BSD-4-Clause

// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:

// Redistributions of source code must retain the above copyright notice, this list
// of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice, this
// list of conditions and the following disclaimer in the documentation and/or other
// materials provided with the distribution.
//
// All advertising materials mentioning features or use of this software must display
// the following acknowledgement: This product includes software developed by Polka Biome
// Ltd., SORA, and Polkaswap.
//
// Neither the name of the Polka Biome Ltd. nor the names of its contributors may be used
// to endorse or promote products derived from this software without specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY Polka Biome Ltd. AS IS AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Polka Biome Ltd. BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
// USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

//! Autogenerated weights for eth_bridge
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-04-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `takemiyotonoMBP.lan`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("local"), DB CACHE: 1024

// Executed Command:
// target/release/framenode
// benchmark
// pallet
// --chain=local
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// eth_bridge
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --header
// ./misc/file_header.txt
// --template
// ./misc/pallet-weight-template.hbs
// --output
// ./pallets/eth-bridge/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for eth_bridge.
#[allow(dead_code)]
pub trait WeightInfo {
	fn register_bridge(p: u32, ) -> Weight;
	fn add_asset() -> Weight;
	fn add_sidechain_token(s: u32, n: u32, ) -> Weight;
	fn transfer_to_sidechain() -> Weight;
	fn request_from_sidechain() -> Weight;
	fn register_incoming_request() -> Weight;
	fn finalize_incoming_request() -> Weight;
	fn approve_request() -> Weight;
	fn add_peer() -> Weight;
	fn remove_peer() -> Weight;
	fn prepare_for_migration() -> Weight;
	fn migrate(a: u32, ) -> Weight;
	fn approve_request_finalize() -> Weight;
	fn force_add_peer() -> Weight;
	fn remove_sidechain_asset() -> Weight;
	fn register_existing_sidechain_asset() -> Weight;
	fn abort_request() -> Weight;
	fn reset_request_signatures() -> Weight;
}

/// Weights for eth_bridge using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `EthBridge::NextNetworkId` (r:1 w:1)
	/// Proof: `EthBridge::NextNetworkId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `BridgeMultisig::Accounts` (r:1 w:1)
	/// Proof: `BridgeMultisig::Accounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeStatuses` (r:0 w:1)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Peers` (r:0 w:1)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeContractAddress` (r:0 w:1)
	/// Proof: `EthBridge::BridgeContractAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:0 w:1)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeAccount` (r:0 w:1)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `p` is `[1, 100]`.
	fn register_bridge(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `617`
		//  Estimated: `6196`
		// Minimum execution time: 32_000_000 picoseconds.
		Weight::from_parts(33_171_138, 6196)
			// Standard Error: 2_066
			.saturating_add(Weight::from_parts(55_714, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: `EthBridge::AuthorityAccount` (r:1 w:0)
	/// Proof: `EthBridge::AuthorityAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::AssetOwners` (r:1 w:0)
	/// Proof: `Assets::AssetOwners` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1477`
		//  Estimated: `4942`
		// Minimum execution time: 53_000_000 picoseconds.
		Weight::from_parts(54_000_000, 4942)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: `EthBridge::AuthorityAccount` (r:1 w:0)
	/// Proof: `EthBridge::AuthorityAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `s` is `[1, 7]`.
	/// The range of component `n` is `[1, 33]`.
	fn add_sidechain_token(s: u32, _n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `957`
		//  Estimated: `4422`
		// Minimum execution time: 46_000_000 picoseconds.
		Weight::from_parts(48_083_758, 4422)
			// Standard Error: 21_891
			.saturating_add(Weight::from_parts(106_190, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LockedAssets` (r:1 w:1)
	/// Proof: `BridgeProxy::LockedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LimitedAssets` (r:1 w:0)
	/// Proof: `BridgeProxy::LimitedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Senders` (r:0 w:1)
	/// Proof: `BridgeProxy::Senders` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Transactions` (r:0 w:1)
	/// Proof: `BridgeProxy::Transactions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn transfer_to_sidechain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1973`
		//  Estimated: `325556`
		// Minimum execution time: 131_000_000 picoseconds.
		Weight::from_parts(134_000_000, 325556)
			.saturating_add(T::DbWeight::get().reads(14_u64))
			.saturating_add(T::DbWeight::get().writes(12_u64))
	}
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request_from_sidechain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `566`
		//  Estimated: `4031`
		// Minimum execution time: 32_000_000 picoseconds.
		Weight::from_parts(34_000_000, 4031)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LockedAssets` (r:1 w:1)
	/// Proof: `BridgeProxy::LockedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:0 w:2)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LoadToIncomingRequestHash` (r:0 w:1)
	/// Proof: `EthBridge::LoadToIncomingRequestHash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_incoming_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `767`
		//  Estimated: `4232`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(38_000_000, 4232)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Tokens::Accounts` (r:1 w:1)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `Tokens::TotalIssuance` (r:1 w:1)
	/// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Senders` (r:0 w:1)
	/// Proof: `BridgeProxy::Senders` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Transactions` (r:0 w:1)
	/// Proof: `BridgeProxy::Transactions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn finalize_incoming_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2854`
		//  Estimated: `325556`
		// Minimum execution time: 77_000_000 picoseconds.
		Weight::from_parts(78_000_000, 325556)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `EthBridge::Peers` (r:1 w:0)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Denomination::Denominator` (r:1 w:0)
	/// Proof: `Denomination::Denominator` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::SidechainAssetPrecision` (r:1 w:0)
	/// Proof: `EthBridge::SidechainAssetPrecision` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeContractAddress` (r:1 w:0)
	/// Proof: `EthBridge::BridgeContractAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PendingPeer` (r:1 w:0)
	/// Proof: `EthBridge::PendingPeer` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:0)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn approve_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2214`
		//  Estimated: `5679`
		// Minimum execution time: 196_000_000 picoseconds.
		Weight::from_parts(203_000_000, 5679)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `EthBridge::AuthorityAccount` (r:1 w:0)
	/// Proof: `EthBridge::AuthorityAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:2 w:2)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:2 w:2)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Peers` (r:1 w:0)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PendingPeer` (r:1 w:1)
	/// Proof: `EthBridge::PendingPeer` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:2)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:2)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:2)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_peer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1292`
		//  Estimated: `7232`
		// Minimum execution time: 84_000_000 picoseconds.
		Weight::from_parts(89_000_000, 7232)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(15_u64))
	}
	/// Storage: `EthBridge::AuthorityAccount` (r:1 w:0)
	/// Proof: `EthBridge::AuthorityAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PeerAddress` (r:1 w:0)
	/// Proof: `EthBridge::PeerAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:2 w:2)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:2 w:2)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Peers` (r:1 w:0)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PendingPeer` (r:1 w:1)
	/// Proof: `EthBridge::PendingPeer` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:2)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:2)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:2)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_peer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1325`
		//  Estimated: `7265`
		// Minimum execution time: 86_000_000 picoseconds.
		Weight::from_parts(90_000_000, 7265)
			.saturating_add(T::DbWeight::get().reads(14_u64))
			.saturating_add(T::DbWeight::get().writes(15_u64))
	}
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AuthorityAccount` (r:1 w:0)
	/// Proof: `EthBridge::AuthorityAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn prepare_for_migration() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `858`
		//  Estimated: `4323`
		// Minimum execution time: 42_000_000 picoseconds.
		Weight::from_parts(44_000_000, 4323)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: `EthBridge::AuthorityAccount` (r:1 w:0)
	/// Proof: `EthBridge::AuthorityAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `a` is `[0, 100]`.
	fn migrate(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `858`
		//  Estimated: `4323`
		// Minimum execution time: 43_000_000 picoseconds.
		Weight::from_parts(45_604_004, 4323)
			// Standard Error: 2_541
			.saturating_add(Weight::from_parts(290_670, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: `EthBridge::Peers` (r:1 w:0)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Denomination::Denominator` (r:1 w:0)
	/// Proof: `Denomination::Denominator` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::SidechainAssetPrecision` (r:1 w:0)
	/// Proof: `EthBridge::SidechainAssetPrecision` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeContractAddress` (r:1 w:0)
	/// Proof: `EthBridge::BridgeContractAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PendingPeer` (r:1 w:0)
	/// Proof: `EthBridge::PendingPeer` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `BridgeProxy::Senders` (r:1 w:0)
	/// Proof: `BridgeProxy::Senders` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Transactions` (r:1 w:1)
	/// Proof: `BridgeProxy::Transactions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn approve_request_finalize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3761`
		//  Estimated: `7226`
		// Minimum execution time: 256_000_000 picoseconds.
		Weight::from_parts(271_000_000, 7226)
			.saturating_add(T::DbWeight::get().reads(18_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `EthBridge::Peers` (r:1 w:1)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeMultisig::Accounts` (r:1 w:1)
	/// Proof: `BridgeMultisig::Accounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PeerAccountId` (r:0 w:1)
	/// Proof: `EthBridge::PeerAccountId` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PeerAddress` (r:0 w:1)
	/// Proof: `EthBridge::PeerAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_add_peer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1081`
		//  Estimated: `4546`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 4546)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::AssetOwners` (r:1 w:0)
	/// Proof: `Assets::AssetOwners` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:1)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainAsset` (r:0 w:1)
	/// Proof: `EthBridge::RegisteredSidechainAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:0 w:1)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::SidechainAssetPrecision` (r:0 w:1)
	/// Proof: `EthBridge::SidechainAssetPrecision` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_sidechain_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1523`
		//  Estimated: `4988`
		// Minimum execution time: 24_000_000 picoseconds.
		Weight::from_parts(25_000_000, 4988)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Assets::AssetOwners` (r:1 w:0)
	/// Proof: `Assets::AssetOwners` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:1)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:0 w:1)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainAsset` (r:0 w:1)
	/// Proof: `EthBridge::RegisteredSidechainAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::SidechainAssetPrecision` (r:0 w:1)
	/// Proof: `EthBridge::SidechainAssetPrecision` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_existing_sidechain_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1683`
		//  Estimated: `5148`
		// Minimum execution time: 26_000_000 picoseconds.
		Weight::from_parts(30_000_000, 5148)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LockedAssets` (r:1 w:1)
	/// Proof: `BridgeProxy::LockedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn abort_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2181`
		//  Estimated: `325556`
		// Minimum execution time: 68_000_000 picoseconds.
		Weight::from_parts(69_000_000, 325556)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:0)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn reset_request_signatures() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `533`
		//  Estimated: `3998`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(16_000_000, 3998)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `EthBridge::NextNetworkId` (r:1 w:1)
	/// Proof: `EthBridge::NextNetworkId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `BridgeMultisig::Accounts` (r:1 w:1)
	/// Proof: `BridgeMultisig::Accounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeStatuses` (r:0 w:1)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Peers` (r:0 w:1)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeContractAddress` (r:0 w:1)
	/// Proof: `EthBridge::BridgeContractAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:0 w:1)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeAccount` (r:0 w:1)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `p` is `[1, 100]`.
	fn register_bridge(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `617`
		//  Estimated: `6196`
		// Minimum execution time: 32_000_000 picoseconds.
		Weight::from_parts(33_171_138, 6196)
			// Standard Error: 2_066
			.saturating_add(Weight::from_parts(55_714, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: `EthBridge::AuthorityAccount` (r:1 w:0)
	/// Proof: `EthBridge::AuthorityAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::AssetOwners` (r:1 w:0)
	/// Proof: `Assets::AssetOwners` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1477`
		//  Estimated: `4942`
		// Minimum execution time: 53_000_000 picoseconds.
		Weight::from_parts(54_000_000, 4942)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: `EthBridge::AuthorityAccount` (r:1 w:0)
	/// Proof: `EthBridge::AuthorityAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `s` is `[1, 7]`.
	/// The range of component `n` is `[1, 33]`.
	fn add_sidechain_token(s: u32, _n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `957`
		//  Estimated: `4422`
		// Minimum execution time: 46_000_000 picoseconds.
		Weight::from_parts(48_083_758, 4422)
			// Standard Error: 21_891
			.saturating_add(Weight::from_parts(106_190, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LockedAssets` (r:1 w:1)
	/// Proof: `BridgeProxy::LockedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LimitedAssets` (r:1 w:0)
	/// Proof: `BridgeProxy::LimitedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Senders` (r:0 w:1)
	/// Proof: `BridgeProxy::Senders` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Transactions` (r:0 w:1)
	/// Proof: `BridgeProxy::Transactions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn transfer_to_sidechain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1973`
		//  Estimated: `325556`
		// Minimum execution time: 131_000_000 picoseconds.
		Weight::from_parts(134_000_000, 325556)
			.saturating_add(RocksDbWeight::get().reads(14_u64))
			.saturating_add(RocksDbWeight::get().writes(12_u64))
	}
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request_from_sidechain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `566`
		//  Estimated: `4031`
		// Minimum execution time: 32_000_000 picoseconds.
		Weight::from_parts(34_000_000, 4031)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LockedAssets` (r:1 w:1)
	/// Proof: `BridgeProxy::LockedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:0 w:2)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::LoadToIncomingRequestHash` (r:0 w:1)
	/// Proof: `EthBridge::LoadToIncomingRequestHash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_incoming_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `767`
		//  Estimated: `4232`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(38_000_000, 4232)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Tokens::Accounts` (r:1 w:1)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `Tokens::TotalIssuance` (r:1 w:1)
	/// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Senders` (r:0 w:1)
	/// Proof: `BridgeProxy::Senders` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Transactions` (r:0 w:1)
	/// Proof: `BridgeProxy::Transactions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn finalize_incoming_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2854`
		//  Estimated: `325556`
		// Minimum execution time: 77_000_000 picoseconds.
		Weight::from_parts(78_000_000, 325556)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `EthBridge::Peers` (r:1 w:0)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Denomination::Denominator` (r:1 w:0)
	/// Proof: `Denomination::Denominator` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::SidechainAssetPrecision` (r:1 w:0)
	/// Proof: `EthBridge::SidechainAssetPrecision` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeContractAddress` (r:1 w:0)
	/// Proof: `EthBridge::BridgeContractAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PendingPeer` (r:1 w:0)
	/// Proof: `EthBridge::PendingPeer` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:0)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn approve_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2214`
		//  Estimated: `5679`
		// Minimum execution time: 196_000_000 picoseconds.
		Weight::from_parts(203_000_000, 5679)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `EthBridge::AuthorityAccount` (r:1 w:0)
	/// Proof: `EthBridge::AuthorityAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:2 w:2)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:2 w:2)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Peers` (r:1 w:0)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PendingPeer` (r:1 w:1)
	/// Proof: `EthBridge::PendingPeer` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:2)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:2)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:2)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_peer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1292`
		//  Estimated: `7232`
		// Minimum execution time: 84_000_000 picoseconds.
		Weight::from_parts(89_000_000, 7232)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(15_u64))
	}
	/// Storage: `EthBridge::AuthorityAccount` (r:1 w:0)
	/// Proof: `EthBridge::AuthorityAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PeerAddress` (r:1 w:0)
	/// Proof: `EthBridge::PeerAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:2 w:2)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:2 w:2)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Peers` (r:1 w:0)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PendingPeer` (r:1 w:1)
	/// Proof: `EthBridge::PendingPeer` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:2)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:2)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:2)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_peer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1325`
		//  Estimated: `7265`
		// Minimum execution time: 86_000_000 picoseconds.
		Weight::from_parts(90_000_000, 7265)
			.saturating_add(RocksDbWeight::get().reads(14_u64))
			.saturating_add(RocksDbWeight::get().writes(15_u64))
	}
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AuthorityAccount` (r:1 w:0)
	/// Proof: `EthBridge::AuthorityAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn prepare_for_migration() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `858`
		//  Estimated: `4323`
		// Minimum execution time: 42_000_000 picoseconds.
		Weight::from_parts(44_000_000, 4323)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: `EthBridge::AuthorityAccount` (r:1 w:0)
	/// Proof: `EthBridge::AuthorityAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::BridgeStatuses` (r:1 w:0)
	/// Proof: `EthBridge::BridgeStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:1)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::AccountRequests` (r:1 w:1)
	/// Proof: `EthBridge::AccountRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestSubmissionHeight` (r:0 w:1)
	/// Proof: `EthBridge::RequestSubmissionHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `a` is `[0, 100]`.
	fn migrate(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `858`
		//  Estimated: `4323`
		// Minimum execution time: 43_000_000 picoseconds.
		Weight::from_parts(45_604_004, 4323)
			// Standard Error: 2_541
			.saturating_add(Weight::from_parts(290_670, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: `EthBridge::Peers` (r:1 w:0)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Denomination::Denominator` (r:1 w:0)
	/// Proof: `Denomination::Denominator` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::SidechainAssetPrecision` (r:1 w:0)
	/// Proof: `EthBridge::SidechainAssetPrecision` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeSignatureVersions` (r:1 w:0)
	/// Proof: `EthBridge::BridgeSignatureVersions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeContractAddress` (r:1 w:0)
	/// Proof: `EthBridge::BridgeContractAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:1 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PendingPeer` (r:1 w:0)
	/// Proof: `EthBridge::PendingPeer` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `BridgeProxy::Senders` (r:1 w:0)
	/// Proof: `BridgeProxy::Senders` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Transactions` (r:1 w:1)
	/// Proof: `BridgeProxy::Transactions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn approve_request_finalize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3761`
		//  Estimated: `7226`
		// Minimum execution time: 256_000_000 picoseconds.
		Weight::from_parts(271_000_000, 7226)
			.saturating_add(RocksDbWeight::get().reads(18_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `EthBridge::Peers` (r:1 w:1)
	/// Proof: `EthBridge::Peers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeMultisig::Accounts` (r:1 w:1)
	/// Proof: `BridgeMultisig::Accounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PeerAccountId` (r:0 w:1)
	/// Proof: `EthBridge::PeerAccountId` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::PeerAddress` (r:0 w:1)
	/// Proof: `EthBridge::PeerAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_add_peer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1081`
		//  Estimated: `4546`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 4546)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::AssetOwners` (r:1 w:0)
	/// Proof: `Assets::AssetOwners` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:1 w:1)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainAsset` (r:0 w:1)
	/// Proof: `EthBridge::RegisteredSidechainAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:0 w:1)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::SidechainAssetPrecision` (r:0 w:1)
	/// Proof: `EthBridge::SidechainAssetPrecision` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_sidechain_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1523`
		//  Estimated: `4988`
		// Minimum execution time: 24_000_000 picoseconds.
		Weight::from_parts(25_000_000, 4988)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Assets::AssetOwners` (r:1 w:0)
	/// Proof: `Assets::AssetOwners` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:1)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainToken` (r:0 w:1)
	/// Proof: `EthBridge::RegisteredSidechainToken` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RegisteredSidechainAsset` (r:0 w:1)
	/// Proof: `EthBridge::RegisteredSidechainAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::SidechainAssetPrecision` (r:0 w:1)
	/// Proof: `EthBridge::SidechainAssetPrecision` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_existing_sidechain_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1683`
		//  Estimated: `5148`
		// Minimum execution time: 26_000_000 picoseconds.
		Weight::from_parts(30_000_000, 5148)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `EthBridge::BridgeAccount` (r:1 w:0)
	/// Proof: `EthBridge::BridgeAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:1)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `EthBridge::RegisteredAsset` (r:1 w:0)
	/// Proof: `EthBridge::RegisteredAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LockedAssets` (r:1 w:1)
	/// Proof: `BridgeProxy::LockedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestsQueue` (r:1 w:1)
	/// Proof: `EthBridge::RequestsQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn abort_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2181`
		//  Estimated: `325556`
		// Minimum execution time: 68_000_000 picoseconds.
		Weight::from_parts(69_000_000, 325556)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `EthBridge::RequestStatuses` (r:1 w:0)
	/// Proof: `EthBridge::RequestStatuses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::Requests` (r:1 w:0)
	/// Proof: `EthBridge::Requests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovers` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthBridge::RequestApprovals` (r:0 w:1)
	/// Proof: `EthBridge::RequestApprovals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn reset_request_signatures() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `533`
		//  Estimated: `3998`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(16_000_000, 3998)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
