name: Bug Report
description: A clear and concise description of what the bug is.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve SORA!
    
  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
      description: What are the preconditions to reproduce the bug ?
   
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: What are the steps to reproduce the bug ?
      placeholder: |
        (e.g.)
        1. Go to 
        2. Click on 
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What is the actual behavior when encountering the bug ?
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
      
  - type: dropdown
    attributes:
      label: Environment
      description: In which environment did the bug occur ?
      multiple: false
      options:
        - label: Development
        - label: Test
        - label: Stage
        - label: Production
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system and version of the OS are you using when encountering the bug?

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. If applicable, add screenshots to help explain your problem.
