// This file is part of the SORA network and Polkaswap app.

// Copyright (c) 2020, 2021, Polka Biome Ltd. All rights reserved.
// SPDX-License-Identifier: BSD-4-Clause

// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:

// Redistributions of source code must retain the above copyright notice, this list
// of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice, this
// list of conditions and the following disclaimer in the documentation and/or other
// materials provided with the distribution.
//
// All advertising materials mentioning features or use of this software must display
// the following acknowledgement: This product includes software developed by Polka Biome
// Ltd., SORA, and Polkaswap.
//
// Neither the name of the Polka Biome Ltd. nor the names of its contributors may be used
// to endorse or promote products derived from this software without specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY Polka Biome Ltd. AS IS AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Polka Biome Ltd. BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
// USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

//! Autogenerated weights for bridge_outbound_channel
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-10-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ef2f8146724e`, CPU: `Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("local"), DB CACHE: 1024

// Executed Command:
// /usr/local/bin/framenode
// benchmark
// pallet
// --chain=local
// --steps=50
// --repeat=20
// --pallet=bridge_outbound_channel
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --header=./misc/file_header.txt
// --template=./misc/pallet-weight-template.hbs
// --output=./pallets/trustless-bridge/bridge-outbound-channel/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for bridge_outbound_channel.
pub trait WeightInfo {
	fn on_initialize(m: u32, p: u32, ) -> Weight;
	fn on_initialize_non_interval() -> Weight;
	fn on_initialize_no_messages() -> Weight;
	fn set_fee() -> Weight;
}

/// Weights for bridge_outbound_channel using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: BridgeOutboundChannel Interval (r:1 w:0)
	/// Proof Skipped: BridgeOutboundChannel Interval (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: BridgeOutboundChannel MessageQueues (r:2 w:1)
	/// Proof Skipped: BridgeOutboundChannel MessageQueues (max_values: None, max_size: None, mode: Measured)
	/// Storage: BridgeOutboundChannel QueuesTotalGas (r:1 w:1)
	/// Proof Skipped: BridgeOutboundChannel QueuesTotalGas (max_values: None, max_size: None, mode: Measured)
	/// Storage: BridgeOutboundChannel ChannelNonces (r:1 w:1)
	/// Proof Skipped: BridgeOutboundChannel ChannelNonces (max_values: None, max_size: None, mode: Measured)
	/// Storage: BridgeProxy Senders (r:20 w:0)
	/// Proof Skipped: BridgeProxy Senders (max_values: None, max_size: None, mode: Measured)
	/// Storage: LeafProvider LatestDigest (r:1 w:1)
	/// Proof Skipped: LeafProvider LatestDigest (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: BridgeOutboundChannel LatestCommitment (r:0 w:1)
	/// Proof Skipped: BridgeOutboundChannel LatestCommitment (max_values: None, max_size: None, mode: Measured)
	/// The range of component `m` is `[1, 20]`.
	/// The range of component `p` is `[0, 256]`.
	fn on_initialize(m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (310 ±0) + p * (20 ±0)`
		//  Estimated: `13844 + m * (3497 ±0) + p * (55 ±0)`
		// Minimum execution time: 60_999_000 picoseconds.
		Weight::from_parts(15_993_162, 13844)
			// Standard Error: 15_684
			.saturating_add(Weight::from_parts(11_785_954, 0).saturating_mul(m.into()))
			// Standard Error: 1_197
			.saturating_add(Weight::from_parts(141_562, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().writes(5_u64))
			.saturating_add(Weight::from_parts(0, 3497).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 55).saturating_mul(p.into()))
	}
	/// Storage: BridgeOutboundChannel Interval (r:1 w:0)
	/// Proof Skipped: BridgeOutboundChannel Interval (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: BridgeOutboundChannel MessageQueues (r:2 w:0)
	/// Proof Skipped: BridgeOutboundChannel MessageQueues (max_values: None, max_size: None, mode: Measured)
	fn on_initialize_non_interval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `382`
		//  Estimated: `6209`
		// Minimum execution time: 15_148_000 picoseconds.
		Weight::from_parts(15_545_000, 6209)
			.saturating_add(T::DbWeight::get().reads(3_u64))
	}
	/// Storage: BridgeOutboundChannel Interval (r:1 w:0)
	/// Proof Skipped: BridgeOutboundChannel Interval (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: BridgeOutboundChannel MessageQueues (r:1 w:0)
	/// Proof Skipped: BridgeOutboundChannel MessageQueues (max_values: None, max_size: None, mode: Measured)
	fn on_initialize_no_messages() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `210`
		//  Estimated: `3390`
		// Minimum execution time: 9_731_000 picoseconds.
		Weight::from_parts(9_935_000, 3390)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: BridgeOutboundChannel Fee (r:0 w:1)
	/// Proof Skipped: BridgeOutboundChannel Fee (max_values: Some(1), max_size: None, mode: Measured)
	fn set_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_793_000 picoseconds.
		Weight::from_parts(4_098_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: BridgeOutboundChannel Interval (r:1 w:0)
	/// Proof Skipped: BridgeOutboundChannel Interval (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: BridgeOutboundChannel MessageQueues (r:2 w:1)
	/// Proof Skipped: BridgeOutboundChannel MessageQueues (max_values: None, max_size: None, mode: Measured)
	/// Storage: BridgeOutboundChannel QueuesTotalGas (r:1 w:1)
	/// Proof Skipped: BridgeOutboundChannel QueuesTotalGas (max_values: None, max_size: None, mode: Measured)
	/// Storage: BridgeOutboundChannel ChannelNonces (r:1 w:1)
	/// Proof Skipped: BridgeOutboundChannel ChannelNonces (max_values: None, max_size: None, mode: Measured)
	/// Storage: BridgeProxy Senders (r:20 w:0)
	/// Proof Skipped: BridgeProxy Senders (max_values: None, max_size: None, mode: Measured)
	/// Storage: LeafProvider LatestDigest (r:1 w:1)
	/// Proof Skipped: LeafProvider LatestDigest (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: BridgeOutboundChannel LatestCommitment (r:0 w:1)
	/// Proof Skipped: BridgeOutboundChannel LatestCommitment (max_values: None, max_size: None, mode: Measured)
	/// The range of component `m` is `[1, 20]`.
	/// The range of component `p` is `[0, 256]`.
	fn on_initialize(m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (310 ±0) + p * (20 ±0)`
		//  Estimated: `13844 + m * (3497 ±0) + p * (55 ±0)`
		// Minimum execution time: 60_999_000 picoseconds.
		Weight::from_parts(15_993_162, 13844)
			// Standard Error: 15_684
			.saturating_add(Weight::from_parts(11_785_954, 0).saturating_mul(m.into()))
			// Standard Error: 1_197
			.saturating_add(Weight::from_parts(141_562, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(m.into())))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
			.saturating_add(Weight::from_parts(0, 3497).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 55).saturating_mul(p.into()))
	}
	/// Storage: BridgeOutboundChannel Interval (r:1 w:0)
	/// Proof Skipped: BridgeOutboundChannel Interval (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: BridgeOutboundChannel MessageQueues (r:2 w:0)
	/// Proof Skipped: BridgeOutboundChannel MessageQueues (max_values: None, max_size: None, mode: Measured)
	fn on_initialize_non_interval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `382`
		//  Estimated: `6209`
		// Minimum execution time: 15_148_000 picoseconds.
		Weight::from_parts(15_545_000, 6209)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
	}
	/// Storage: BridgeOutboundChannel Interval (r:1 w:0)
	/// Proof Skipped: BridgeOutboundChannel Interval (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: BridgeOutboundChannel MessageQueues (r:1 w:0)
	/// Proof Skipped: BridgeOutboundChannel MessageQueues (max_values: None, max_size: None, mode: Measured)
	fn on_initialize_no_messages() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `210`
		//  Estimated: `3390`
		// Minimum execution time: 9_731_000 picoseconds.
		Weight::from_parts(9_935_000, 3390)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: BridgeOutboundChannel Fee (r:0 w:1)
	/// Proof Skipped: BridgeOutboundChannel Fee (max_values: Some(1), max_size: None, mode: Measured)
	fn set_fee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_793_000 picoseconds.
		Weight::from_parts(4_098_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
