version: "3.5"
name: sora2-substrate

services:
  sora-alice:
    image: sora2/substrate-local
    container_name: bridge-sora-alice
    restart: always
    build:
      context: ..
      dockerfile: bridge-docker/Dockerfile.sora
    ports:
      - "127.0.0.1:9944:9944"
      - "127.0.0.1:9954:9954"
    command: ["framenode", 
        "--pruning", "archive",
        "--enable-offchain-indexing", "true",
        "-d", "/data", 
        "--alice", 
        "--port", "10000", 
        "--experimental-rpc-endpoint", "listen-addr=0.0.0.0:9944,methods=safe,cors=http://localhost:*,cors=http://127.0.0.1:*",
        "--experimental-rpc-endpoint", "listen-addr=0.0.0.0:9954,methods=safe,cors=http://localhost:*,cors=http://127.0.0.1:*",
        "--chain", "docker-local", 
        "--execution", "wasm", 
        "--wasm-execution", "compiled"
      ]
    volumes:
      - sora-alice-data:/data
    networks:
      - bridgenet
    
volumes:
  sora-alice-data: null

networks:
  bridgenet:
    name: bridgenet
