import argparse
import json
from pathlib import Path

from scalecodec.types import GenericCall
from substrateinterface import Keypair, SubstrateInterface
from substrateinterface.exceptions import SubstrateRequestException

SS58_FORMAT = 69
DEFAULT_NODE_URL = "wss://ws.mof.sora.org"
DEFAULT_FAST_TRACK_DELAY = 0


def parse_args():
    parser = argparse.ArgumentParser(
        prog="Runtime Upgrade",
        description="Submit runtime-upgrade governance extrinsics for a Substrate node",
    )
    parser.add_argument(
        "--node-url",
        dest="node_url",
        default=DEFAULT_NODE_URL,
        help=f"Node websocket URL for signed extrinsic submission (default: {DEFAULT_NODE_URL})",
    )

    auth = parser.add_mutually_exclusive_group(required=True)
    auth.add_argument("--uri", dest="uri_keypair", type=str, help="URI of the keypair to use")
    auth.add_argument("--seed", dest="seed", type=str, help="Seed of the keypair to use")
    auth.add_argument(
        "--mnemonic", dest="mnemonic", type=str, help="Seed phrase of the keypair to use"
    )

    subparsers = parser.add_subparsers(dest="command", required=True)

    note_preimage = subparsers.add_parser(
        "note-preimage",
        help="Submit Preimage.note_preimage with SCALE-encoded call bytes",
    )
    note_preimage.add_argument(
        "--call-file-path",
        required=True,
        help="Path to the raw SCALE-encoded call bytes generated by generate_preimage.py",
    )

    council = subparsers.add_parser(
        "council-propose-majority",
        help="Submit Council.propose(Democracy.external_propose_majority(...))",
    )
    add_preimage_args(council, require_hash_and_len=True)
    council.add_argument(
        "--threshold",
        type=int,
        help="Council voting threshold. Defaults to ceil(current_council_members / 2).",
    )

    tech = subparsers.add_parser(
        "tech-fast-track",
        help="Submit TechnicalCommittee.propose(Democracy.fast_track(...))",
    )
    add_preimage_args(tech, require_hash_and_len=False)
    tech.add_argument(
        "--threshold",
        type=int,
        help="Technical committee voting threshold. Defaults to floor(members / 2) + 1.",
    )
    tech.add_argument(
        "--voting-period",
        type=int,
        help="Fast-track voting period in blocks. Defaults to Democracy.FastTrackVotingPeriod.",
    )
    tech.add_argument(
        "--delay",
        type=int,
        default=DEFAULT_FAST_TRACK_DELAY,
        help=f"Enactment delay in blocks (default: {DEFAULT_FAST_TRACK_DELAY})",
    )

    sudo = subparsers.add_parser(
        "sudo-set-code",
        help="Dev-only helper for networks that still expose Sudo",
    )
    sudo.add_argument(
        "--wasm-file-path",
        required=True,
        help="Path to the runtime wasm blob",
    )
    sudo.add_argument(
        "--unchecked",
        action="store_true",
        default=False,
        help="Call System.set_code_without_checks inside sudo_unchecked_weight",
    )

    return parser.parse_args()


def add_preimage_args(parser, require_hash_and_len):
    parser.add_argument(
        "--preimage-json",
        help="Path to the JSON summary generated by generate_preimage.py",
    )
    parser.add_argument(
        "--proposal-hash",
        help="Proposal hash (0x...) from generate_preimage.py",
        required=False,
    )
    if require_hash_and_len:
        parser.add_argument(
            "--proposal-len",
            type=int,
            help="Proposal length from generate_preimage.py",
            required=False,
        )


def get_keypair_using_args(args):
    if args.uri_keypair:
        return Keypair.create_from_uri(args.uri_keypair, ss58_format=SS58_FORMAT)
    if args.seed:
        return Keypair.create_from_seed(args.seed, ss58_format=SS58_FORMAT)
    if args.mnemonic:
        return Keypair.create_from_mnemonic(args.mnemonic, ss58_format=SS58_FORMAT)
    raise ValueError("No keypair provided")


def send_extrinsic(substrate_provider: SubstrateInterface, keypair: Keypair, call: GenericCall):
    extrinsic = substrate_provider.create_signed_extrinsic(call=call, keypair=keypair)
    try:
        receipt = substrate_provider.submit_extrinsic(extrinsic, wait_for_finalization=True)
        log_receipt(receipt)
    except SubstrateRequestException as exc:
        print(f"Error in send_extrinsic: {exc}")
        raise


def log_receipt(receipt):
    print(f'Extrinsic "{receipt.extrinsic_hash}" included in block "{receipt.block_hash}"')
    if receipt.is_success:
        print("Success, triggered events:")
        for event in receipt.triggered_events:
            print(f"* {event.value}")
        return
    raise RuntimeError(f"Extrinsic failed: {receipt.error_message}")


def get_new_code_from_wasm_file(wasm_file_path):
    with open(wasm_file_path, "rb") as file_handle:
        return "0x" + file_handle.read().hex()


def get_call_bytes_from_file(call_file_path):
    with open(call_file_path, "rb") as file_handle:
        return "0x" + file_handle.read().hex()


def load_preimage_metadata(args):
    data = {}
    if getattr(args, "preimage_json", None):
        with open(args.preimage_json, "r", encoding="utf-8") as file_handle:
            data.update(json.load(file_handle))

    proposal_hash = getattr(args, "proposal_hash", None) or data.get("proposal_hash")
    proposal_len = getattr(args, "proposal_len", None)
    if proposal_len is None:
        proposal_len = data.get("proposal_len")

    return proposal_hash, proposal_len


def scale_value(value):
    return value.value if hasattr(value, "value") else value


def query_members(substrate: SubstrateInterface, pallet: str):
    members = scale_value(substrate.query(pallet, "Members"))
    if not members:
        raise RuntimeError(f"{pallet}.Members is empty")
    return members


def get_threshold(args, substrate: SubstrateInterface, pallet: str, strict_majority: bool):
    if args.threshold is not None:
        return args.threshold

    members = query_members(substrate, pallet)
    size = len(members)
    if strict_majority:
        return size // 2 + 1
    return (size + 1) // 2


def get_fast_track_voting_period(args, substrate: SubstrateInterface):
    if args.voting_period is not None:
        return args.voting_period
    constant = substrate.get_constant("Democracy", "FastTrackVotingPeriod")
    return scale_value(constant)


def compose_bounded_lookup_call(substrate: SubstrateInterface, proposal_hash: str, proposal_len: int):
    return substrate.compose_call(
        call_module="Democracy",
        call_function="external_propose_majority",
        call_params={
            "proposal": {
                "Lookup": {
                    "hash": proposal_hash,
                    "len": proposal_len,
                }
            }
        },
    )


def compose_council_motion(substrate: SubstrateInterface, proposal_hash: str, proposal_len: int, threshold: int):
    proposal = compose_bounded_lookup_call(substrate, proposal_hash, proposal_len)
    return substrate.compose_call(
        call_module="Council",
        call_function="propose",
        call_params={
            "threshold": threshold,
            "proposal": proposal,
            "length_bound": len(proposal.data),
        },
    )


def compose_fast_track_motion(
    substrate: SubstrateInterface,
    proposal_hash: str,
    threshold: int,
    voting_period: int,
    delay: int,
):
    proposal = substrate.compose_call(
        call_module="Democracy",
        call_function="fast_track",
        call_params={
            "proposal_hash": proposal_hash,
            "voting_period": voting_period,
            "delay": delay,
        },
    )
    return substrate.compose_call(
        call_module="TechnicalCommittee",
        call_function="propose",
        call_params={
            "threshold": threshold,
            "proposal": proposal,
            "length_bound": len(proposal.data),
        },
    )


def handle_note_preimage(substrate: SubstrateInterface, args):
    return substrate.compose_call(
        call_module="Preimage",
        call_function="note_preimage",
        call_params={"bytes": get_call_bytes_from_file(args.call_file_path)},
    )


def handle_council_propose_majority(substrate: SubstrateInterface, args):
    proposal_hash, proposal_len = load_preimage_metadata(args)
    if not proposal_hash or proposal_len is None:
        raise ValueError(
            "council-propose-majority requires --proposal-hash and --proposal-len, or --preimage-json"
        )

    threshold = get_threshold(args, substrate, "Council", strict_majority=False)
    print(
        f"Submitting Council.propose for Democracy.external_propose_majority with threshold={threshold}, "
        f"proposal_hash={proposal_hash}, proposal_len={proposal_len}"
    )
    return compose_council_motion(substrate, proposal_hash, int(proposal_len), threshold)


def handle_tech_fast_track(substrate: SubstrateInterface, args):
    proposal_hash, _proposal_len = load_preimage_metadata(args)
    if not proposal_hash:
        raise ValueError("tech-fast-track requires --proposal-hash or --preimage-json")

    threshold = get_threshold(args, substrate, "TechnicalCommittee", strict_majority=True)
    voting_period = get_fast_track_voting_period(args, substrate)
    print(
        f"Submitting TechnicalCommittee.propose for Democracy.fast_track with threshold={threshold}, "
        f"proposal_hash={proposal_hash}, voting_period={voting_period}, delay={args.delay}"
    )
    return compose_fast_track_motion(
        substrate,
        proposal_hash,
        threshold,
        int(voting_period),
        int(args.delay),
    )


def handle_sudo_set_code(substrate: SubstrateInterface, args):
    set_code_call = substrate.compose_call(
        call_module="System",
        call_function="set_code_without_checks" if args.unchecked else "set_code",
        call_params={"code": get_new_code_from_wasm_file(args.wasm_file_path)},
    )

    if args.unchecked:
        last_upgrade_key = substrate.generate_storage_hash(
            storage_module="System",
            storage_function="LastRuntimeUpgrade",
        )
        kill_storage_call = substrate.compose_call(
            call_module="System",
            call_function="kill_storage",
            call_params={"keys": [last_upgrade_key]},
        )
        inner_call = substrate.compose_call(
            call_module="Utility",
            call_function="batch_all",
            call_params={"calls": [kill_storage_call, set_code_call]},
        )
    else:
        inner_call = set_code_call

    return substrate.compose_call(
        call_module="Sudo",
        call_function="sudo_unchecked_weight",
        call_params={
            "call": inner_call,
            "weight": {"ref_time": 0, "proof_size": 0},
        },
    )


def compose_command_call(substrate: SubstrateInterface, args):
    if args.command == "note-preimage":
        return handle_note_preimage(substrate, args)
    if args.command == "council-propose-majority":
        return handle_council_propose_majority(substrate, args)
    if args.command == "tech-fast-track":
        return handle_tech_fast_track(substrate, args)
    if args.command == "sudo-set-code":
        return handle_sudo_set_code(substrate, args)
    raise ValueError(f"Unsupported command: {args.command}")


def main():
    substrate = None
    try:
        args = parse_args()
        keypair = get_keypair_using_args(args)
        substrate = SubstrateInterface(url=args.node_url, ss58_format=SS58_FORMAT)
        call = compose_command_call(substrate, args)
        send_extrinsic(substrate, keypair, call)
    except Exception as exc:
        print(f"Error: {exc}")
        raise
    finally:
        if substrate:
            substrate.close()


if __name__ == "__main__":
    main()
