name: SCCP Fuzz Nightly

on:
  schedule:
    - cron: "45 03 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ubuntu-22.04
    timeout-minutes: 240

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup Rust nightly toolchain
        run: |
          rustup toolchain install "nightly-2025-08-06" --profile minimal
          rustup default "nightly-2025-08-06"

      - name: Cache cargo
        uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8
      - name: Run fuzz CI suite
        run: bash ./scripts/test_ci_fuzz.sh
