// This file is part of the SORA network and Polkaswap app.

// Copyright (c) 2020, 2021, Polka Biome Ltd. All rights reserved.
// SPDX-License-Identifier: BSD-4-Clause

// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:

// Redistributions of source code must retain the above copyright notice, this list
// of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice, this
// list of conditions and the following disclaimer in the documentation and/or other
// materials provided with the distribution.
//
// All advertising materials mentioning features or use of this software must display
// the following acknowledgement: This product includes software developed by Polka Biome
// Ltd., SORA, and Polkaswap.
//
// Neither the name of the Polka Biome Ltd. nor the names of its contributors may be used
// to endorse or promote products derived from this software without specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY Polka Biome Ltd. AS IS AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Polka Biome Ltd. BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
// USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

//! Autogenerated weights for kensetsu
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-12-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `587b4c89f56b`, CPU: `Intel(R) Xeon(R) CPU E3-1240 v6 @ 3.70GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("local"), DB CACHE: 1024

// Executed Command:
// /usr/local/bin/framenode
// benchmark
// pallet
// --chain=local
// --steps=50
// --repeat=20
// --pallet=kensetsu
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --header=./misc/file_header.txt
// --template=./misc/pallet-weight-template.hbs
// --output=./pallets/kensetsu/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for kensetsu.
pub trait WeightInfo {
	fn create_cdp() -> Weight;
	fn close_cdp() -> Weight;
	fn deposit_collateral() -> Weight;
	fn borrow() -> Weight;
	fn repay_debt() -> Weight;
	fn liquidate() -> Weight;
	fn accrue() -> Weight;
	fn update_collateral_risk_parameters() -> Weight;
	fn update_borrow_tax() -> Weight;
	fn update_liquidation_penalty() -> Weight;
	fn withdraw_profit() -> Weight;
	fn donate() -> Weight;
	fn register_stablecoin() -> Weight;
	fn update_hard_cap() -> Weight;
	fn update_liquidation_ratio() -> Weight;
	fn update_max_liquidation_lot() -> Weight;
	fn update_stability_fee_rate() -> Weight;
	fn update_minimal_collateral_deposit() -> Weight;
	fn update_minimal_stability_fee_accrue() -> Weight;
}

/// Weights for kensetsu using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Kensetsu NextCDPId (r:1 w:1)
	/// Proof: Kensetsu NextCDPId (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Kensetsu CdpOwnerIndex (r:1 w:1)
	/// Proof: Kensetsu CdpOwnerIndex (max_values: None, max_size: Some(160034), added: 162509, mode: MaxEncodedLen)
	/// Storage: Technical TechAccounts (r:2 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:2 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:2 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:0)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:2 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: PriceTools FastPriceInfos (r:1 w:0)
	/// Proof Skipped: PriceTools FastPriceInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Kensetsu BorrowTax (r:1 w:0)
	/// Proof: Kensetsu BorrowTax (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	/// Storage: Kensetsu CDPDepository (r:0 w:1)
	/// Proof: Kensetsu CDPDepository (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	fn create_cdp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6536`
		//  Estimated: `878642`
		// Minimum execution time: 327_393_000 picoseconds.
		Weight::from_parts(335_318_000, 878642)
			.saturating_add(T::DbWeight::get().reads(19_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: Kensetsu CDPDepository (r:1 w:1)
	/// Proof: Kensetsu CDPDepository (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:0)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:2 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfosV2 (r:2 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:2 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:2 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Kensetsu CdpOwnerIndex (r:1 w:1)
	/// Proof: Kensetsu CdpOwnerIndex (max_values: None, max_size: Some(160034), added: 162509, mode: MaxEncodedLen)
	fn close_cdp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3012`
		//  Estimated: `846815`
		// Minimum execution time: 230_540_000 picoseconds.
		Weight::from_parts(231_475_000, 846815)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: Kensetsu CDPDepository (r:1 w:1)
	/// Proof: Kensetsu CDPDepository (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: Technical TechAccounts (r:1 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	fn deposit_collateral() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2610`
		//  Estimated: `345240`
		// Minimum execution time: 138_436_000 picoseconds.
		Weight::from_parts(139_334_000, 345240)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: Kensetsu CDPDepository (r:1 w:1)
	/// Proof: Kensetsu CDPDepository (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:0)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:1 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:2 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: PriceTools FastPriceInfos (r:1 w:0)
	/// Proof Skipped: PriceTools FastPriceInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Kensetsu BorrowTax (r:1 w:0)
	/// Proof: Kensetsu BorrowTax (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	fn borrow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6100`
		//  Estimated: `381355`
		// Minimum execution time: 209_807_000 picoseconds.
		Weight::from_parts(214_927_000, 381355)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: Kensetsu CDPDepository (r:1 w:1)
	/// Proof: Kensetsu CDPDepository (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:0)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:1 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:2 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	fn repay_debt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3659`
		//  Estimated: `362520`
		// Minimum execution time: 216_747_000 picoseconds.
		Weight::from_parts(219_652_000, 362520)
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: Kensetsu LiquidatedThisBlock (r:1 w:1)
	/// Proof: Kensetsu LiquidatedThisBlock (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	/// Storage: Kensetsu CDPDepository (r:1 w:1)
	/// Proof: Kensetsu CDPDepository (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:1)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:3 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfosV2 (r:2 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:2 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:2 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: PriceTools FastPriceInfos (r:2 w:1)
	/// Proof Skipped: PriceTools FastPriceInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: DEXManager DEXInfos (r:1 w:0)
	/// Proof Skipped: DEXManager DEXInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: XSTPool EnabledSynthetics (r:2 w:0)
	/// Proof Skipped: XSTPool EnabledSynthetics (max_values: None, max_size: None, mode: Measured)
	/// Storage: DEXAPI EnabledSourceTypes (r:1 w:0)
	/// Proof Skipped: DEXAPI EnabledSourceTypes (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: PoolXYK Properties (r:1 w:0)
	/// Proof Skipped: PoolXYK Properties (max_values: None, max_size: None, mode: Measured)
	/// Storage: MulticollateralBondingCurvePool EnabledTargets (r:1 w:0)
	/// Proof Skipped: MulticollateralBondingCurvePool EnabledTargets (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: OrderBook OrderBooks (r:1 w:0)
	/// Proof: OrderBook OrderBooks (max_values: None, max_size: Some(238), added: 2713, mode: MaxEncodedLen)
	/// Storage: TradingPair LockedLiquiditySources (r:1 w:0)
	/// Proof Skipped: TradingPair LockedLiquiditySources (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: System Account (r:4 w:4)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Kensetsu LiquidationPenalty (r:1 w:0)
	/// Proof: Kensetsu LiquidationPenalty (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	/// Storage: Assets AssetOwners (r:1 w:0)
	/// Proof Skipped: Assets AssetOwners (max_values: None, max_size: None, mode: Measured)
	/// Storage: PriceTools PriceInfos (r:1 w:1)
	/// Proof Skipped: PriceTools PriceInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	/// Storage: PoolXYK Reserves (r:0 w:1)
	/// Proof Skipped: PoolXYK Reserves (max_values: None, max_size: None, mode: Measured)
	fn liquidate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10611`
		//  Estimated: `866442`
		// Minimum execution time: 790_181_000 picoseconds.
		Weight::from_parts(792_049_000, 866442)
			.saturating_add(T::DbWeight::get().reads(34_u64))
			.saturating_add(T::DbWeight::get().writes(14_u64))
	}
	/// Storage: Kensetsu CDPDepository (r:1 w:1)
	/// Proof: Kensetsu CDPDepository (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:0)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:1 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:2 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	fn accrue() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2882`
		//  Estimated: `354270`
		// Minimum execution time: 125_069_000 picoseconds.
		Weight::from_parts(125_453_000, 354270)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: PriceTools FastPriceInfos (r:1 w:0)
	/// Proof Skipped: PriceTools FastPriceInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetOwners (r:1 w:0)
	/// Proof Skipped: Assets AssetOwners (max_values: None, max_size: None, mode: Measured)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:0)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	fn update_collateral_risk_parameters() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1580`
		//  Estimated: `15331`
		// Minimum execution time: 66_010_000 picoseconds.
		Weight::from_parts(66_623_000, 15331)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Kensetsu BorrowTax (r:1 w:1)
	/// Proof: Kensetsu BorrowTax (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	/// Storage: Kensetsu KarmaBorrowTax (r:1 w:1)
	/// Proof: Kensetsu KarmaBorrowTax (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	/// Storage: Kensetsu TbcdBorrowTax (r:1 w:1)
	/// Proof: Kensetsu TbcdBorrowTax (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	fn update_borrow_tax() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `218`
		//  Estimated: `1488`
		// Minimum execution time: 29_730_000 picoseconds.
		Weight::from_parts(30_009_000, 1488)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: Kensetsu LiquidationPenalty (r:1 w:1)
	/// Proof: Kensetsu LiquidationPenalty (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	fn update_liquidation_penalty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `218`
		//  Estimated: `496`
		// Minimum execution time: 22_627_000 picoseconds.
		Weight::from_parts(22_938_000, 496)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Kensetsu StablecoinInfos (r:1 w:0)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:1 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn withdraw_profit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2465`
		//  Estimated: `349814`
		// Minimum execution time: 137_675_000 picoseconds.
		Weight::from_parts(138_287_000, 349814)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: Technical TechAccounts (r:1 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:1)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	fn donate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2949`
		//  Estimated: `353797`
		// Minimum execution time: 174_018_000 picoseconds.
		Weight::from_parts(175_106_000, 353797)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: Assets AssetInfosV2 (r:1 w:1)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetOwners (r:3 w:1)
	/// Proof Skipped: Assets AssetOwners (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Permissions Owners (r:2 w:2)
	/// Proof Skipped: Permissions Owners (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:3 w:1)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:1)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: DEXManager DEXInfos (r:1 w:0)
	/// Proof Skipped: DEXManager DEXInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: TradingPair EnabledSources (r:1 w:1)
	/// Proof Skipped: TradingPair EnabledSources (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfos (r:0 w:1)
	/// Proof Skipped: Assets AssetInfos (max_values: None, max_size: None, mode: Measured)
	fn register_stablecoin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3567`
		//  Estimated: `60839`
		// Minimum execution time: 262_678_000 picoseconds.
		Weight::from_parts(263_856_000, 60839)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	fn update_hard_cap() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `462`
		//  Estimated: `2663`
		// Minimum execution time: 28_136_000 picoseconds.
		Weight::from_parts(28_547_000, 2663)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	fn update_liquidation_ratio() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `462`
		//  Estimated: `2663`
		// Minimum execution time: 27_542_000 picoseconds.
		Weight::from_parts(28_215_000, 2663)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	fn update_max_liquidation_lot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `462`
		//  Estimated: `2663`
		// Minimum execution time: 27_730_000 picoseconds.
		Weight::from_parts(27_995_000, 2663)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	fn update_stability_fee_rate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `504`
		//  Estimated: `3166`
		// Minimum execution time: 36_445_000 picoseconds.
		Weight::from_parts(37_017_000, 3166)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	fn update_minimal_collateral_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `462`
		//  Estimated: `2663`
		// Minimum execution time: 28_342_000 picoseconds.
		Weight::from_parts(28_724_000, 2663)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Kensetsu StablecoinInfos (r:1 w:1)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	fn update_minimal_stability_fee_accrue() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `480`
		//  Estimated: `2955`
		// Minimum execution time: 28_924_000 picoseconds.
		Weight::from_parts(29_308_000, 2955)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Kensetsu NextCDPId (r:1 w:1)
	/// Proof: Kensetsu NextCDPId (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Kensetsu CdpOwnerIndex (r:1 w:1)
	/// Proof: Kensetsu CdpOwnerIndex (max_values: None, max_size: Some(160034), added: 162509, mode: MaxEncodedLen)
	/// Storage: Technical TechAccounts (r:2 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:2 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:2 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:0)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:2 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: PriceTools FastPriceInfos (r:1 w:0)
	/// Proof Skipped: PriceTools FastPriceInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Kensetsu BorrowTax (r:1 w:0)
	/// Proof: Kensetsu BorrowTax (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	/// Storage: Kensetsu CDPDepository (r:0 w:1)
	/// Proof: Kensetsu CDPDepository (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	fn create_cdp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6536`
		//  Estimated: `878642`
		// Minimum execution time: 327_393_000 picoseconds.
		Weight::from_parts(335_318_000, 878642)
			.saturating_add(RocksDbWeight::get().reads(19_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: Kensetsu CDPDepository (r:1 w:1)
	/// Proof: Kensetsu CDPDepository (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:0)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:2 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfosV2 (r:2 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:2 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:2 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Kensetsu CdpOwnerIndex (r:1 w:1)
	/// Proof: Kensetsu CdpOwnerIndex (max_values: None, max_size: Some(160034), added: 162509, mode: MaxEncodedLen)
	fn close_cdp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3012`
		//  Estimated: `846815`
		// Minimum execution time: 230_540_000 picoseconds.
		Weight::from_parts(231_475_000, 846815)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: Kensetsu CDPDepository (r:1 w:1)
	/// Proof: Kensetsu CDPDepository (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: Technical TechAccounts (r:1 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	fn deposit_collateral() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2610`
		//  Estimated: `345240`
		// Minimum execution time: 138_436_000 picoseconds.
		Weight::from_parts(139_334_000, 345240)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: Kensetsu CDPDepository (r:1 w:1)
	/// Proof: Kensetsu CDPDepository (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:0)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:1 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:2 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: PriceTools FastPriceInfos (r:1 w:0)
	/// Proof Skipped: PriceTools FastPriceInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Kensetsu BorrowTax (r:1 w:0)
	/// Proof: Kensetsu BorrowTax (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	fn borrow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6100`
		//  Estimated: `381355`
		// Minimum execution time: 209_807_000 picoseconds.
		Weight::from_parts(214_927_000, 381355)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: Kensetsu CDPDepository (r:1 w:1)
	/// Proof: Kensetsu CDPDepository (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:0)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:1 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:2 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	fn repay_debt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3659`
		//  Estimated: `362520`
		// Minimum execution time: 216_747_000 picoseconds.
		Weight::from_parts(219_652_000, 362520)
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: Kensetsu LiquidatedThisBlock (r:1 w:1)
	/// Proof: Kensetsu LiquidatedThisBlock (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	/// Storage: Kensetsu CDPDepository (r:1 w:1)
	/// Proof: Kensetsu CDPDepository (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:1)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:3 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfosV2 (r:2 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:2 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:2 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: PriceTools FastPriceInfos (r:2 w:1)
	/// Proof Skipped: PriceTools FastPriceInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: DEXManager DEXInfos (r:1 w:0)
	/// Proof Skipped: DEXManager DEXInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: XSTPool EnabledSynthetics (r:2 w:0)
	/// Proof Skipped: XSTPool EnabledSynthetics (max_values: None, max_size: None, mode: Measured)
	/// Storage: DEXAPI EnabledSourceTypes (r:1 w:0)
	/// Proof Skipped: DEXAPI EnabledSourceTypes (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: PoolXYK Properties (r:1 w:0)
	/// Proof Skipped: PoolXYK Properties (max_values: None, max_size: None, mode: Measured)
	/// Storage: MulticollateralBondingCurvePool EnabledTargets (r:1 w:0)
	/// Proof Skipped: MulticollateralBondingCurvePool EnabledTargets (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: OrderBook OrderBooks (r:1 w:0)
	/// Proof: OrderBook OrderBooks (max_values: None, max_size: Some(238), added: 2713, mode: MaxEncodedLen)
	/// Storage: TradingPair LockedLiquiditySources (r:1 w:0)
	/// Proof Skipped: TradingPair LockedLiquiditySources (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: System Account (r:4 w:4)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Kensetsu LiquidationPenalty (r:1 w:0)
	/// Proof: Kensetsu LiquidationPenalty (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	/// Storage: Assets AssetOwners (r:1 w:0)
	/// Proof Skipped: Assets AssetOwners (max_values: None, max_size: None, mode: Measured)
	/// Storage: PriceTools PriceInfos (r:1 w:1)
	/// Proof Skipped: PriceTools PriceInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	/// Storage: PoolXYK Reserves (r:0 w:1)
	/// Proof Skipped: PoolXYK Reserves (max_values: None, max_size: None, mode: Measured)
	fn liquidate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10611`
		//  Estimated: `866442`
		// Minimum execution time: 790_181_000 picoseconds.
		Weight::from_parts(792_049_000, 866442)
			.saturating_add(RocksDbWeight::get().reads(34_u64))
			.saturating_add(RocksDbWeight::get().writes(14_u64))
	}
	/// Storage: Kensetsu CDPDepository (r:1 w:1)
	/// Proof: Kensetsu CDPDepository (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:0)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:1 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:2 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	fn accrue() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2882`
		//  Estimated: `354270`
		// Minimum execution time: 125_069_000 picoseconds.
		Weight::from_parts(125_453_000, 354270)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: PriceTools FastPriceInfos (r:1 w:0)
	/// Proof Skipped: PriceTools FastPriceInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetOwners (r:1 w:0)
	/// Proof Skipped: Assets AssetOwners (max_values: None, max_size: None, mode: Measured)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:0)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	fn update_collateral_risk_parameters() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1580`
		//  Estimated: `15331`
		// Minimum execution time: 66_010_000 picoseconds.
		Weight::from_parts(66_623_000, 15331)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Kensetsu BorrowTax (r:1 w:1)
	/// Proof: Kensetsu BorrowTax (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	/// Storage: Kensetsu KarmaBorrowTax (r:1 w:1)
	/// Proof: Kensetsu KarmaBorrowTax (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	/// Storage: Kensetsu TbcdBorrowTax (r:1 w:1)
	/// Proof: Kensetsu TbcdBorrowTax (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	fn update_borrow_tax() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `218`
		//  Estimated: `1488`
		// Minimum execution time: 29_730_000 picoseconds.
		Weight::from_parts(30_009_000, 1488)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: Kensetsu LiquidationPenalty (r:1 w:1)
	/// Proof: Kensetsu LiquidationPenalty (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
	fn update_liquidation_penalty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `218`
		//  Estimated: `496`
		// Minimum execution time: 22_627_000 picoseconds.
		Weight::from_parts(22_938_000, 496)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Kensetsu StablecoinInfos (r:1 w:0)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:1 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn withdraw_profit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2465`
		//  Estimated: `349814`
		// Minimum execution time: 137_675_000 picoseconds.
		Weight::from_parts(138_287_000, 349814)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: Technical TechAccounts (r:1 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:1)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	fn donate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2949`
		//  Estimated: `353797`
		// Minimum execution time: 174_018_000 picoseconds.
		Weight::from_parts(175_106_000, 353797)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: Assets AssetInfosV2 (r:1 w:1)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetOwners (r:3 w:1)
	/// Proof Skipped: Assets AssetOwners (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Permissions Owners (r:2 w:2)
	/// Proof Skipped: Permissions Owners (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:3 w:1)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: Kensetsu StablecoinInfos (r:1 w:1)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: DEXManager DEXInfos (r:1 w:0)
	/// Proof Skipped: DEXManager DEXInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: TradingPair EnabledSources (r:1 w:1)
	/// Proof Skipped: TradingPair EnabledSources (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfos (r:0 w:1)
	/// Proof Skipped: Assets AssetInfos (max_values: None, max_size: None, mode: Measured)
	fn register_stablecoin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3567`
		//  Estimated: `60839`
		// Minimum execution time: 262_678_000 picoseconds.
		Weight::from_parts(263_856_000, 60839)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	fn update_hard_cap() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `462`
		//  Estimated: `2663`
		// Minimum execution time: 28_136_000 picoseconds.
		Weight::from_parts(28_547_000, 2663)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	fn update_liquidation_ratio() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `462`
		//  Estimated: `2663`
		// Minimum execution time: 27_542_000 picoseconds.
		Weight::from_parts(28_215_000, 2663)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	fn update_max_liquidation_lot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `462`
		//  Estimated: `2663`
		// Minimum execution time: 27_730_000 picoseconds.
		Weight::from_parts(27_995_000, 2663)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	fn update_stability_fee_rate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `504`
		//  Estimated: `3166`
		// Minimum execution time: 36_445_000 picoseconds.
		Weight::from_parts(37_017_000, 3166)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Kensetsu CollateralInfos (r:1 w:1)
	/// Proof: Kensetsu CollateralInfos (max_values: None, max_size: Some(188), added: 2663, mode: MaxEncodedLen)
	fn update_minimal_collateral_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `462`
		//  Estimated: `2663`
		// Minimum execution time: 28_342_000 picoseconds.
		Weight::from_parts(28_724_000, 2663)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Kensetsu StablecoinInfos (r:1 w:1)
	/// Proof Skipped: Kensetsu StablecoinInfos (max_values: None, max_size: None, mode: Measured)
	fn update_minimal_stability_fee_accrue() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `480`
		//  Estimated: `2955`
		// Minimum execution time: 28_924_000 picoseconds.
		Weight::from_parts(29_308_000, 2955)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
