// This file is part of the SORA network and Polkaswap app.

// Copyright (c) 2020, 2021, Polka Biome Ltd. All rights reserved.
// SPDX-License-Identifier: BSD-4-Clause

// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:

// Redistributions of source code must retain the above copyright notice, this list
// of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice, this
// list of conditions and the following disclaimer in the documentation and/or other
// materials provided with the distribution.
//
// All advertising materials mentioning features or use of this software must display
// the following acknowledgement: This product includes software developed by Polka Biome
// Ltd., SORA, and Polkaswap.
//
// Neither the name of the Polka Biome Ltd. nor the names of its contributors may be used
// to endorse or promote products derived from this software without specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY Polka Biome Ltd. AS IS AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Polka Biome Ltd. BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
// USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//! Autogenerated weights for `dispatch`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-31, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `takemiyacStudio.lan`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/debug/framenode
// benchmark
// pallet
// --runtime=target/debug/wbuild/framenode-runtime/framenode_runtime.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=benchmark
// --steps=50
// --repeat=20
// --pallet=dispatch
// --extrinsic=*
// --wasm-execution=compiled
// --header=/Users/mtakemiya/dev/sora2-network/misc/file_header.txt
// --output=/Users/mtakemiya/dev/sora2-network/runtime/src/weights/dispatch.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `dispatch`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> dispatch::WeightInfo for WeightInfo<T> {
	/// Storage: `JettonApp::AssetsByAddresses` (r:1 w:0)
	/// Proof: `JettonApp::AssetsByAddresses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `JettonApp::AssetKinds` (r:1 w:0)
	/// Proof: `JettonApp::AssetKinds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `JettonApp::AppInfo` (r:1 w:0)
	/// Proof: `JettonApp::AppInfo` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `JettonApp::SidechainPrecision` (r:1 w:0)
	/// Proof: `JettonApp::SidechainPrecision` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Denomination::Denominator` (r:1 w:0)
	/// Proof: `Denomination::Denominator` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::LockedAssets` (r:1 w:1)
	/// Proof: `BridgeProxy::LockedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Technical::TechAccounts` (r:1 w:0)
	/// Proof: `Technical::TechAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Permissions::Permissions` (r:1 w:0)
	/// Proof: `Permissions::Permissions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `BridgeProxy::Senders` (r:0 w:1)
	/// Proof: `BridgeProxy::Senders` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeProxy::Transactions` (r:0 w:1)
	/// Proof: `BridgeProxy::Transactions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn dispatch_success() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1050`
		//  Estimated: `325556`
		// Minimum execution time: 1_085_000_000 picoseconds.
		Weight::from_parts(1_148_000_000, 0)
			.saturating_add(Weight::from_parts(0, 325556))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	fn dispatch_decode_failed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 39_000_000 picoseconds.
		Weight::from_parts(41_000_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
