// This file is part of the SORA network and Polkaswap app.

// Copyright (c) 2020, 2021, Polka Biome Ltd. All rights reserved.
// SPDX-License-Identifier: BSD-4-Clause

// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:

// Redistributions of source code must retain the above copyright notice, this list
// of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice, this
// list of conditions and the following disclaimer in the documentation and/or other
// materials provided with the distribution.
//
// All advertising materials mentioning features or use of this software must display
// the following acknowledgement: This product includes software developed by Polka Biome
// Ltd., SORA, and Polkaswap.
//
// Neither the name of the Polka Biome Ltd. nor the names of its contributors may be used
// to endorse or promote products derived from this software without specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY Polka Biome Ltd. AS IS AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Polka Biome Ltd. BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
// USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

//! Autogenerated weights for pallet_polkamarkt
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-06-03, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `takemiyamakotonoMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// /Users/takemiyamakoto/dev/sora2-network/target/release/framenode
// benchmark
// pallet
// --runtime=/Users/takemiyamakoto/dev/sora2-network/target/release/wbuild/framenode-runtime/framenode_runtime.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=benchmark
// --steps=50
// --repeat=20
// --pallet=pallet_polkamarkt
// --extrinsic=*
// --wasm-execution=compiled
// --header=/Users/takemiyamakoto/dev/sora2-network/misc/file_header.txt
// --output=/Users/takemiyamakoto/dev/sora2-network/runtime/src/weights/polkamarkt.rs
// --template=/Users/takemiyamakoto/dev/sora2-network/misc/polkamarkt-runtime-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_polkamarkt.
#[allow(dead_code)]
pub trait WeightInfo {
	fn create_condition() -> Weight;
	fn create_condition_with_details() -> Weight;
	fn create_market() -> Weight;
	fn buy() -> Weight;
	fn sell() -> Weight;
	fn sync_market_status() -> Weight;
	fn resolve_market() -> Weight;
	fn resolve_market_with_evidence() -> Weight;
	fn report_early_resolution() -> Weight;
	fn reject_early_resolution_report() -> Weight;
	fn cancel_market() -> Weight;
	fn emergency_cancel_market() -> Weight;
	fn claim_market() -> Weight;
	fn claim_markets(n: u32, ) -> Weight;
	fn claim_creator_fees() -> Weight;
	fn sweep_xor_buyback_and_burn() -> Weight;
}

/// Weights for pallet_polkamarkt using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Polkamarkt::NextConditionId` (r:1 w:1)
	/// Proof: `Polkamarkt::NextConditionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::FeeCollectorOverride` (r:1 w:0)
	/// Proof: `Polkamarkt::FeeCollectorOverride` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:3 w:3)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Polkamarkt::PendingXorBuybackCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::PendingXorBuybackCollateral` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::ConditionCreators` (r:0 w:1)
	/// Proof: `Polkamarkt::ConditionCreators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::Conditions` (r:0 w:1)
	/// Proof: `Polkamarkt::Conditions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_condition() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `981`
		//  Estimated: `325556`
		// Minimum execution time: 65_000_000 picoseconds.
		Weight::from_parts(76_000_000, 325556)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
	/// Storage: `Polkamarkt::NextConditionId` (r:1 w:1)
	/// Proof: `Polkamarkt::NextConditionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::FeeCollectorOverride` (r:1 w:0)
	/// Proof: `Polkamarkt::FeeCollectorOverride` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:3 w:3)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Polkamarkt::PendingXorBuybackCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::PendingXorBuybackCollateral` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::ConditionDetails` (r:0 w:1)
	/// Proof: `Polkamarkt::ConditionDetails` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::ConditionCreators` (r:0 w:1)
	/// Proof: `Polkamarkt::ConditionCreators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::Conditions` (r:0 w:1)
	/// Proof: `Polkamarkt::Conditions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_condition_with_details() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `981`
		//  Estimated: `325556`
		// Minimum execution time: 70_000_000 picoseconds.
		Weight::from_parts(81_000_000, 325556)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(10_u64))
	}
	/// Storage: `Polkamarkt::NextMarketId` (r:1 w:1)
	/// Proof: `Polkamarkt::NextMarketId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::Conditions` (r:1 w:0)
	/// Proof: `Polkamarkt::Conditions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::ConditionCreators` (r:1 w:0)
	/// Proof: `Polkamarkt::ConditionCreators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::ConditionMarket` (r:1 w:1)
	/// Proof: `Polkamarkt::ConditionMarket` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::Markets` (r:0 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `322`
		//  Estimated: `3787`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(20_000_000, 3787)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositionTotals` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketPositionTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositions` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:2 w:2)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Polkamarkt::MarketCreatorFees` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketCreatorFees` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::PendingXorBuybackCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::PendingXorBuybackCollateral` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketDpmCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketDpmCollateral` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketVolume` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketVolume` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisByAccount` (r:1 w:1)
	/// Proof: `Polkamarkt::DpmCostBasisByAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisTotals` (r:1 w:1)
	/// Proof: `Polkamarkt::DpmCostBasisTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn buy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1493`
		//  Estimated: `325556`
		// Minimum execution time: 83_000_000 picoseconds.
		Weight::from_parts(96_000_000, 325556)
			.saturating_add(T::DbWeight::get().reads(14_u64))
			.saturating_add(T::DbWeight::get().writes(11_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositions` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositionTotals` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketPositionTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketDpmCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketDpmCollateral` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketCreatorFees` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketCreatorFees` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::PendingXorBuybackCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::PendingXorBuybackCollateral` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketVolume` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketVolume` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisByAccount` (r:1 w:1)
	/// Proof: `Polkamarkt::DpmCostBasisByAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisTotals` (r:1 w:1)
	/// Proof: `Polkamarkt::DpmCostBasisTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:2 w:2)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn sell() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2137`
		//  Estimated: `325556`
		// Minimum execution time: 97_000_000 picoseconds.
		Weight::from_parts(114_000_000, 325556)
			.saturating_add(T::DbWeight::get().reads(14_u64))
			.saturating_add(T::DbWeight::get().writes(11_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sync_market_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `408`
		//  Estimated: `3873`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3873)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositionTotals` (r:1 w:0)
	/// Proof: `Polkamarkt::MarketPositionTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketDpmCollateral` (r:1 w:0)
	/// Proof: `Polkamarkt::MarketDpmCollateral` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketResolution` (r:0 w:1)
	/// Proof: `Polkamarkt::MarketResolution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn resolve_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `408`
		//  Estimated: `3873`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(24_000_000, 3873)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositionTotals` (r:1 w:0)
	/// Proof: `Polkamarkt::MarketPositionTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketDpmCollateral` (r:1 w:0)
	/// Proof: `Polkamarkt::MarketDpmCollateral` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketResolutionEvidence` (r:0 w:1)
	/// Proof: `Polkamarkt::MarketResolutionEvidence` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketResolution` (r:0 w:1)
	/// Proof: `Polkamarkt::MarketResolution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn resolve_market_with_evidence() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `408`
		//  Estimated: `3873`
		// Minimum execution time: 24_000_000 picoseconds.
		Weight::from_parts(28_000_000, 3873)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	fn report_early_resolution() -> Weight {
		Weight::from_parts(82_000_000, 325556)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	fn reject_early_resolution_report() -> Weight {
		Weight::from_parts(31_000_000, 3873)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketResolution` (r:0 w:1)
	/// Proof: `Polkamarkt::MarketResolution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `408`
		//  Estimated: `3873`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(19_000_000, 3873)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketCancellationEvidence` (r:0 w:1)
	/// Proof: `Polkamarkt::MarketCancellationEvidence` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketResolution` (r:0 w:1)
	/// Proof: `Polkamarkt::MarketResolution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn emergency_cancel_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `408`
		//  Estimated: `3873`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(19_000_000, 3873)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositions` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisByAccount` (r:1 w:1)
	/// Proof: `Polkamarkt::DpmCostBasisByAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketResolution` (r:1 w:0)
	/// Proof: `Polkamarkt::MarketResolution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositionTotals` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketPositionTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketDpmCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketDpmCollateral` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisTotals` (r:1 w:1)
	/// Proof: `Polkamarkt::DpmCostBasisTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:2 w:2)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2102`
		//  Estimated: `325556`
		// Minimum execution time: 62_000_000 picoseconds.
		Weight::from_parts(72_000_000, 325556)
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:24 w:24)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositions` (r:24 w:24)
	/// Proof: `Polkamarkt::MarketPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisByAccount` (r:24 w:24)
	/// Proof: `Polkamarkt::DpmCostBasisByAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketResolution` (r:24 w:0)
	/// Proof: `Polkamarkt::MarketResolution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositionTotals` (r:24 w:24)
	/// Proof: `Polkamarkt::MarketPositionTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketDpmCollateral` (r:24 w:24)
	/// Proof: `Polkamarkt::MarketDpmCollateral` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisTotals` (r:24 w:24)
	/// Proof: `Polkamarkt::DpmCostBasisTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:2 w:2)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 24]`.
	fn claim_markets(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1589 + n * (546 ±0)`
		//  Estimated: `325556 + n * (3022 ±0)`
		// Minimum execution time: 65_000_000 picoseconds.
		Weight::from_parts(20_595_149, 325556)
			// Standard Error: 57_048
			.saturating_add(Weight::from_parts(54_471_340, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().reads((7_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((6_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3022).saturating_mul(n.into()))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:0)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketCreatorFees` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketCreatorFees` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:2 w:2)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_creator_fees() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1768`
		//  Estimated: `325556`
		// Minimum execution time: 41_000_000 picoseconds.
		Weight::from_parts(47_000_000, 325556)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Polkamarkt::PendingXorBuybackCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::PendingXorBuybackCollateral` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `DEXManager::DEXInfos` (r:1 w:0)
	/// Proof: `DEXManager::DEXInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `XSTPool::EnabledSynthetics` (r:1 w:0)
	/// Proof: `XSTPool::EnabledSynthetics` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `DEXAPI::EnabledSourceTypes` (r:1 w:0)
	/// Proof: `DEXAPI::EnabledSourceTypes` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `PoolXYK::Properties` (r:1 w:0)
	/// Proof: `PoolXYK::Properties` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OrderBook::OrderBooks` (r:1 w:0)
	/// Proof: `OrderBook::OrderBooks` (`max_values`: None, `max_size`: Some(238), added: 2713, mode: `MaxEncodedLen`)
	/// Storage: `TradingPair::LockedLiquiditySources` (r:1 w:0)
	/// Proof: `TradingPair::LockedLiquiditySources` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Tokens::Accounts` (r:2 w:2)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:2 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:2 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Technical::TechAccounts` (r:1 w:0)
	/// Proof: `Technical::TechAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PriceTools::PriceInfos` (r:1 w:1)
	/// Proof: `PriceTools::PriceInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PriceTools::FastPriceInfos` (r:1 w:1)
	/// Proof: `PriceTools::FastPriceInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PoolXYK::Reserves` (r:0 w:1)
	/// Proof: `PoolXYK::Reserves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sweep_xor_buyback_and_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5092`
		//  Estimated: `650122`
		// Minimum execution time: 239_000_000 picoseconds.
		Weight::from_parts(277_000_000, 650122)
			.saturating_add(T::DbWeight::get().reads(19_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
}

/// Runtime-specific alias.
pub type SoraWeight<T> = SubstrateWeight<T>;

impl<T: frame_system::Config + pallet_polkamarkt::Config> pallet_polkamarkt::WeightInfo
	for SoraWeight<T>
{
	fn create_condition() -> Weight {
		<SubstrateWeight<T> as WeightInfo>::create_condition()
	}
	fn create_condition_with_details() -> Weight {
		<SubstrateWeight<T> as WeightInfo>::create_condition_with_details()
	}
	fn create_market() -> Weight {
		<SubstrateWeight<T> as WeightInfo>::create_market()
	}
	fn buy() -> Weight {
		<SubstrateWeight<T> as WeightInfo>::buy()
	}
	fn sell() -> Weight {
		<SubstrateWeight<T> as WeightInfo>::sell()
	}
	fn sync_market_status() -> Weight {
		<SubstrateWeight<T> as WeightInfo>::sync_market_status()
	}
	fn resolve_market() -> Weight {
		<SubstrateWeight<T> as WeightInfo>::resolve_market()
	}
	fn resolve_market_with_evidence() -> Weight {
		<SubstrateWeight<T> as WeightInfo>::resolve_market_with_evidence()
	}
	fn report_early_resolution() -> Weight {
		<SubstrateWeight<T> as WeightInfo>::report_early_resolution()
	}
	fn reject_early_resolution_report() -> Weight {
		<SubstrateWeight<T> as WeightInfo>::reject_early_resolution_report()
	}
	fn cancel_market() -> Weight {
		<SubstrateWeight<T> as WeightInfo>::cancel_market()
	}
	fn emergency_cancel_market() -> Weight {
		<SubstrateWeight<T> as WeightInfo>::emergency_cancel_market()
	}
	fn claim_market() -> Weight {
		<SubstrateWeight<T> as WeightInfo>::claim_market()
	}
	fn claim_markets(n: u32, ) -> Weight {
		<SubstrateWeight<T> as WeightInfo>::claim_markets(n, )
	}
	fn claim_creator_fees() -> Weight {
		<SubstrateWeight<T> as WeightInfo>::claim_creator_fees()
	}
	fn sweep_xor_buyback_and_burn() -> Weight {
		<SubstrateWeight<T> as WeightInfo>::sweep_xor_buyback_and_burn()
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `Polkamarkt::NextConditionId` (r:1 w:1)
	/// Proof: `Polkamarkt::NextConditionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::FeeCollectorOverride` (r:1 w:0)
	/// Proof: `Polkamarkt::FeeCollectorOverride` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:3 w:3)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Polkamarkt::PendingXorBuybackCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::PendingXorBuybackCollateral` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::ConditionCreators` (r:0 w:1)
	/// Proof: `Polkamarkt::ConditionCreators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::Conditions` (r:0 w:1)
	/// Proof: `Polkamarkt::Conditions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_condition() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `981`
		//  Estimated: `325556`
		// Minimum execution time: 65_000_000 picoseconds.
		Weight::from_parts(76_000_000, 325556)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
	/// Storage: `Polkamarkt::NextConditionId` (r:1 w:1)
	/// Proof: `Polkamarkt::NextConditionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::FeeCollectorOverride` (r:1 w:0)
	/// Proof: `Polkamarkt::FeeCollectorOverride` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:3 w:3)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Polkamarkt::PendingXorBuybackCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::PendingXorBuybackCollateral` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::ConditionDetails` (r:0 w:1)
	/// Proof: `Polkamarkt::ConditionDetails` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::ConditionCreators` (r:0 w:1)
	/// Proof: `Polkamarkt::ConditionCreators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::Conditions` (r:0 w:1)
	/// Proof: `Polkamarkt::Conditions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_condition_with_details() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `981`
		//  Estimated: `325556`
		// Minimum execution time: 70_000_000 picoseconds.
		Weight::from_parts(81_000_000, 325556)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(10_u64))
	}
	/// Storage: `Polkamarkt::NextMarketId` (r:1 w:1)
	/// Proof: `Polkamarkt::NextMarketId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::Conditions` (r:1 w:0)
	/// Proof: `Polkamarkt::Conditions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::ConditionCreators` (r:1 w:0)
	/// Proof: `Polkamarkt::ConditionCreators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::ConditionMarket` (r:1 w:1)
	/// Proof: `Polkamarkt::ConditionMarket` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::Markets` (r:0 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `322`
		//  Estimated: `3787`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(20_000_000, 3787)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositionTotals` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketPositionTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositions` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:2 w:2)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Polkamarkt::MarketCreatorFees` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketCreatorFees` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::PendingXorBuybackCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::PendingXorBuybackCollateral` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketDpmCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketDpmCollateral` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketVolume` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketVolume` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisByAccount` (r:1 w:1)
	/// Proof: `Polkamarkt::DpmCostBasisByAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisTotals` (r:1 w:1)
	/// Proof: `Polkamarkt::DpmCostBasisTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn buy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1493`
		//  Estimated: `325556`
		// Minimum execution time: 83_000_000 picoseconds.
		Weight::from_parts(96_000_000, 325556)
			.saturating_add(RocksDbWeight::get().reads(14_u64))
			.saturating_add(RocksDbWeight::get().writes(11_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositions` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositionTotals` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketPositionTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketDpmCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketDpmCollateral` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketCreatorFees` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketCreatorFees` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::PendingXorBuybackCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::PendingXorBuybackCollateral` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketVolume` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketVolume` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisByAccount` (r:1 w:1)
	/// Proof: `Polkamarkt::DpmCostBasisByAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisTotals` (r:1 w:1)
	/// Proof: `Polkamarkt::DpmCostBasisTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:2 w:2)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn sell() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2137`
		//  Estimated: `325556`
		// Minimum execution time: 97_000_000 picoseconds.
		Weight::from_parts(114_000_000, 325556)
			.saturating_add(RocksDbWeight::get().reads(14_u64))
			.saturating_add(RocksDbWeight::get().writes(11_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sync_market_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `408`
		//  Estimated: `3873`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3873)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositionTotals` (r:1 w:0)
	/// Proof: `Polkamarkt::MarketPositionTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketDpmCollateral` (r:1 w:0)
	/// Proof: `Polkamarkt::MarketDpmCollateral` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketResolution` (r:0 w:1)
	/// Proof: `Polkamarkt::MarketResolution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn resolve_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `408`
		//  Estimated: `3873`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(24_000_000, 3873)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositionTotals` (r:1 w:0)
	/// Proof: `Polkamarkt::MarketPositionTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketDpmCollateral` (r:1 w:0)
	/// Proof: `Polkamarkt::MarketDpmCollateral` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketResolutionEvidence` (r:0 w:1)
	/// Proof: `Polkamarkt::MarketResolutionEvidence` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketResolution` (r:0 w:1)
	/// Proof: `Polkamarkt::MarketResolution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn resolve_market_with_evidence() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `408`
		//  Estimated: `3873`
		// Minimum execution time: 24_000_000 picoseconds.
		Weight::from_parts(28_000_000, 3873)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	fn report_early_resolution() -> Weight {
		Weight::from_parts(82_000_000, 325556)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	fn reject_early_resolution_report() -> Weight {
		Weight::from_parts(31_000_000, 3873)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketResolution` (r:0 w:1)
	/// Proof: `Polkamarkt::MarketResolution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `408`
		//  Estimated: `3873`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(19_000_000, 3873)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketCancellationEvidence` (r:0 w:1)
	/// Proof: `Polkamarkt::MarketCancellationEvidence` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketResolution` (r:0 w:1)
	/// Proof: `Polkamarkt::MarketResolution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn emergency_cancel_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `408`
		//  Estimated: `3873`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(19_000_000, 3873)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:1)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositions` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisByAccount` (r:1 w:1)
	/// Proof: `Polkamarkt::DpmCostBasisByAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketResolution` (r:1 w:0)
	/// Proof: `Polkamarkt::MarketResolution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositionTotals` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketPositionTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketDpmCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketDpmCollateral` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisTotals` (r:1 w:1)
	/// Proof: `Polkamarkt::DpmCostBasisTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:2 w:2)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2102`
		//  Estimated: `325556`
		// Minimum execution time: 62_000_000 picoseconds.
		Weight::from_parts(72_000_000, 325556)
			.saturating_add(RocksDbWeight::get().reads(12_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: `Polkamarkt::Markets` (r:24 w:24)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositions` (r:24 w:24)
	/// Proof: `Polkamarkt::MarketPositions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisByAccount` (r:24 w:24)
	/// Proof: `Polkamarkt::DpmCostBasisByAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketResolution` (r:24 w:0)
	/// Proof: `Polkamarkt::MarketResolution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketPositionTotals` (r:24 w:24)
	/// Proof: `Polkamarkt::MarketPositionTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketDpmCollateral` (r:24 w:24)
	/// Proof: `Polkamarkt::MarketDpmCollateral` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::DpmCostBasisTotals` (r:24 w:24)
	/// Proof: `Polkamarkt::DpmCostBasisTotals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:2 w:2)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 24]`.
	fn claim_markets(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1589 + n * (546 ±0)`
		//  Estimated: `325556 + n * (3022 ±0)`
		// Minimum execution time: 65_000_000 picoseconds.
		Weight::from_parts(20_595_149, 325556)
			// Standard Error: 57_048
			.saturating_add(Weight::from_parts(54_471_340, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().reads((7_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(RocksDbWeight::get().writes((6_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3022).saturating_mul(n.into()))
	}
	/// Storage: `Polkamarkt::Markets` (r:1 w:0)
	/// Proof: `Polkamarkt::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarkt::MarketCreatorFees` (r:1 w:1)
	/// Proof: `Polkamarkt::MarketCreatorFees` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:1 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:1 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::Accounts` (r:2 w:2)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_creator_fees() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1768`
		//  Estimated: `325556`
		// Minimum execution time: 41_000_000 picoseconds.
		Weight::from_parts(47_000_000, 325556)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Polkamarkt::PendingXorBuybackCollateral` (r:1 w:1)
	/// Proof: `Polkamarkt::PendingXorBuybackCollateral` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `DEXManager::DEXInfos` (r:1 w:0)
	/// Proof: `DEXManager::DEXInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `XSTPool::EnabledSynthetics` (r:1 w:0)
	/// Proof: `XSTPool::EnabledSynthetics` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `DEXAPI::EnabledSourceTypes` (r:1 w:0)
	/// Proof: `DEXAPI::EnabledSourceTypes` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `PoolXYK::Properties` (r:1 w:0)
	/// Proof: `PoolXYK::Properties` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OrderBook::OrderBooks` (r:1 w:0)
	/// Proof: `OrderBook::OrderBooks` (`max_values`: None, `max_size`: Some(238), added: 2713, mode: `MaxEncodedLen`)
	/// Storage: `TradingPair::LockedLiquiditySources` (r:1 w:0)
	/// Proof: `TradingPair::LockedLiquiditySources` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Tokens::Accounts` (r:2 w:2)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `ExtendedAssets::SoulboundAsset` (r:2 w:0)
	/// Proof: `ExtendedAssets::SoulboundAsset` (`max_values`: None, `max_size`: Some(322091), added: 324566, mode: `MaxEncodedLen`)
	/// Storage: `Assets::AssetInfosV2` (r:2 w:0)
	/// Proof: `Assets::AssetInfosV2` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Technical::TechAccounts` (r:1 w:0)
	/// Proof: `Technical::TechAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PriceTools::PriceInfos` (r:1 w:1)
	/// Proof: `PriceTools::PriceInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PriceTools::FastPriceInfos` (r:1 w:1)
	/// Proof: `PriceTools::FastPriceInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `PoolXYK::Reserves` (r:0 w:1)
	/// Proof: `PoolXYK::Reserves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sweep_xor_buyback_and_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5092`
		//  Estimated: `650122`
		// Minimum execution time: 239_000_000 picoseconds.
		Weight::from_parts(277_000_000, 650122)
			.saturating_add(RocksDbWeight::get().reads(19_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
}
