// This file is part of the SORA network and Polkaswap app.

// Copyright (c) 2020, 2021, Polka Biome Ltd. All rights reserved.
// SPDX-License-Identifier: BSD-4-Clause

// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:

// Redistributions of source code must retain the above copyright notice, this list
// of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice, this
// list of conditions and the following disclaimer in the documentation and/or other
// materials provided with the distribution.
//
// All advertising materials mentioning features or use of this software must display
// the following acknowledgement: This product includes software developed by Polka Biome
// Ltd., SORA, and Polkaswap.
//
// Neither the name of the Polka Biome Ltd. nor the names of its contributors may be used
// to endorse or promote products derived from this software without specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY Polka Biome Ltd. AS IS AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Polka Biome Ltd. BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
// USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

//! Autogenerated weights for `presto`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-12-10, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Local`, CPU: `12th Gen Intel(R) Core(TM) i5-12600K`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("local"), DB CACHE: 1024

// Executed Command:
// target/release/framenode
// benchmark
// pallet
// --chain=local
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// presto
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./benches

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for presto.
pub trait WeightInfo {
    fn add_presto_manager() -> Weight;
    fn remove_presto_manager() -> Weight;
    fn add_presto_auditor() -> Weight;
    fn remove_presto_auditor() -> Weight;
    fn mint_presto_usd() -> Weight;
    fn burn_presto_usd() -> Weight;
    fn send_presto_usd() -> Weight;
    fn create_deposit_request() -> Weight;
    fn create_withdraw_request() -> Weight;
    fn cancel_request() -> Weight;
    fn approve_deposit_request() -> Weight;
    fn approve_withdraw_request() -> Weight;
    fn decline_request() -> Weight;
    fn create_crop_receipt() -> Weight;
    fn rate_crop_receipt() -> Weight;
    fn decline_crop_receipt() -> Weight;
    fn publish_crop_receipt() -> Weight;
}

/// Weight functions for `presto`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Presto Managers (r:1 w:1)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	fn add_presto_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3697`
		// Minimum execution time: 6_617 nanoseconds.
		Weight::from_parts(7_100_000, 3697)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Presto Managers (r:1 w:1)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	fn remove_presto_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `167`
		//  Estimated: `3697`
		// Minimum execution time: 7_713 nanoseconds.
		Weight::from_parts(8_696_000, 3697)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Presto Auditors (r:1 w:1)
	/// Proof: Presto Auditors (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	fn add_presto_auditor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3697`
		// Minimum execution time: 6_256 nanoseconds.
		Weight::from_parts(6_909_000, 3697)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Presto Auditors (r:1 w:1)
	/// Proof: Presto Auditors (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	fn remove_presto_auditor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `167`
		//  Estimated: `3697`
		// Minimum execution time: 7_677 nanoseconds.
		Weight::from_parts(8_145_000, 3697)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Presto Managers (r:1 w:0)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:1 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn mint_presto_usd() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2120`
		//  Estimated: `345198`
		// Minimum execution time: 39_146 nanoseconds.
		Weight::from_parts(41_702_000, 345198)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Presto Managers (r:1 w:0)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	fn burn_presto_usd() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1716`
		//  Estimated: `337596`
		// Minimum execution time: 29_891 nanoseconds.
		Weight::from_parts(31_087_000, 337596)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: Presto Managers (r:1 w:0)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn send_presto_usd() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1838`
		//  Estimated: `343004`
		// Minimum execution time: 37_014 nanoseconds.
		Weight::from_parts(38_331_000, 343004)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Presto LastRequestId (r:1 w:1)
	/// Proof: Presto LastRequestId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Presto UserRequests (r:1 w:1)
	/// Proof: Presto UserRequests (max_values: None, max_size: Some(524332), added: 526807, mode: MaxEncodedLen)
	/// Storage: Presto Requests (r:0 w:1)
	/// Proof: Presto Requests (max_values: None, max_size: Some(420), added: 2895, mode: MaxEncodedLen)
	fn create_deposit_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `256`
		//  Estimated: `527813`
		// Minimum execution time: 10_917 nanoseconds.
		Weight::from_parts(11_705_000, 527813)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Presto LastRequestId (r:1 w:1)
	/// Proof: Presto LastRequestId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Presto UserRequests (r:1 w:1)
	/// Proof: Presto UserRequests (max_values: None, max_size: Some(524332), added: 526807, mode: MaxEncodedLen)
	/// Storage: Presto Requests (r:0 w:1)
	/// Proof: Presto Requests (max_values: None, max_size: Some(420), added: 2895, mode: MaxEncodedLen)
	fn create_withdraw_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2064`
		//  Estimated: `867346`
		// Minimum execution time: 45_444 nanoseconds.
		Weight::from_parts(47_933_000, 867346)
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: Presto Requests (r:1 w:1)
	/// Proof: Presto Requests (max_values: None, max_size: Some(420), added: 2895, mode: MaxEncodedLen)
	fn cancel_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `298`
		//  Estimated: `2895`
		// Minimum execution time: 8_267 nanoseconds.
		Weight::from_parts(8_626_000, 2895)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Presto Managers (r:1 w:0)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	/// Storage: Presto Requests (r:1 w:1)
	/// Proof: Presto Requests (max_values: None, max_size: Some(420), added: 2895, mode: MaxEncodedLen)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	fn approve_deposit_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2236`
		//  Estimated: `346800`
		// Minimum execution time: 45_051 nanoseconds.
		Weight::from_parts(47_826_000, 346800)
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Presto Managers (r:1 w:0)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	/// Storage: Presto Requests (r:1 w:1)
	/// Proof: Presto Requests (max_values: None, max_size: Some(420), added: 2895, mode: MaxEncodedLen)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	fn approve_withdraw_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2359`
		//  Estimated: `344320`
		// Minimum execution time: 42_741 nanoseconds.
		Weight::from_parts(44_619_000, 344320)
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Presto Managers (r:1 w:0)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	/// Storage: Presto Requests (r:1 w:1)
	/// Proof: Presto Requests (max_values: None, max_size: Some(420), added: 2895, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	fn decline_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `565`
		//  Estimated: `7095`
		// Minimum execution time: 11_711 nanoseconds.
		Weight::from_parts(12_575_000, 7095)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Presto LastCropReceiptId (r:1 w:1)
	/// Proof: Presto LastCropReceiptId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Presto UserCropReceipts (r:1 w:1)
	/// Proof: Presto UserCropReceipts (max_values: None, max_size: Some(524332), added: 526807, mode: MaxEncodedLen)
	/// Storage: Presto CropReceiptsContent (r:0 w:1)
	/// Proof: Presto CropReceiptsContent (max_values: None, max_size: Some(30740), added: 33215, mode: MaxEncodedLen)
	/// Storage: Presto CropReceipts (r:0 w:1)
	/// Proof: Presto CropReceipts (max_values: None, max_size: Some(398), added: 2873, mode: MaxEncodedLen)
	fn create_crop_receipt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `256`
		//  Estimated: `527813`
		// Minimum execution time: 15_160 nanoseconds.
		Weight::from_parts(16_304_000, 527813)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Presto Auditors (r:1 w:0)
	/// Proof: Presto Auditors (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	/// Storage: Presto CropReceipts (r:1 w:1)
	/// Proof: Presto CropReceipts (max_values: None, max_size: Some(398), added: 2873, mode: MaxEncodedLen)
	fn rate_crop_receipt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `429`
		//  Estimated: `6570`
		// Minimum execution time: 10_366 nanoseconds.
		Weight::from_parts(11_125_000, 6570)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Presto CropReceipts (r:1 w:1)
	/// Proof: Presto CropReceipts (max_values: None, max_size: Some(398), added: 2873, mode: MaxEncodedLen)
	fn decline_crop_receipt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `408`
		//  Estimated: `2873`
		// Minimum execution time: 8_628 nanoseconds.
		Weight::from_parts(9_092_000, 2873)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Presto CropReceipts (r:1 w:1)
	/// Proof: Presto CropReceipts (max_values: None, max_size: Some(398), added: 2873, mode: MaxEncodedLen)
	/// Storage: Presto LastCouponId (r:1 w:1)
	/// Proof: Presto LastCouponId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: System Account (r:3 w:3)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Assets AssetOwners (r:2 w:1)
	/// Proof Skipped: Assets AssetOwners (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Owners (r:2 w:2)
	/// Proof Skipped: Permissions Owners (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:3 w:1)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:3 w:3)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: DEXManager DEXInfos (r:1 w:0)
	/// Proof Skipped: DEXManager DEXInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: TradingPair EnabledSources (r:1 w:1)
	/// Proof Skipped: TradingPair EnabledSources (max_values: None, max_size: None, mode: Measured)
	/// Storage: OrderBook OrderBooks (r:1 w:1)
	/// Proof: OrderBook OrderBooks (max_values: None, max_size: Some(238), added: 2713, mode: MaxEncodedLen)
	/// Storage: Technical TechAccounts (r:1 w:1)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: OrderBook UserLimitOrders (r:1 w:1)
	/// Proof: OrderBook UserLimitOrders (max_values: None, max_size: Some(16518), added: 18993, mode: MaxEncodedLen)
	/// Storage: OrderBook Asks (r:1 w:1)
	/// Proof: OrderBook Asks (max_values: None, max_size: Some(16503), added: 18978, mode: MaxEncodedLen)
	/// Storage: OrderBook AggregatedAsks (r:1 w:1)
	/// Proof: OrderBook AggregatedAsks (max_values: None, max_size: Some(34902), added: 37377, mode: MaxEncodedLen)
	/// Storage: OrderBook AggregatedBids (r:1 w:0)
	/// Proof: OrderBook AggregatedBids (max_values: None, max_size: Some(34902), added: 37377, mode: MaxEncodedLen)
	/// Storage: OrderBook LimitOrders (r:1 w:1)
	/// Proof: OrderBook LimitOrders (max_values: None, max_size: Some(236), added: 2711, mode: MaxEncodedLen)
	/// Storage: OrderBook ExpirationsAgenda (r:1 w:1)
	/// Proof: OrderBook ExpirationsAgenda (max_values: None, max_size: Some(86022), added: 88497, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:0 w:1)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfos (r:0 w:1)
	/// Proof Skipped: Assets AssetInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Presto Coupons (r:0 w:1)
	/// Proof: Presto Coupons (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	fn publish_crop_receipt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5096`
		//  Estimated: `618782`
		// Minimum execution time: 217_008 nanoseconds.
		Weight::from_parts(226_387_000, 618782)
			.saturating_add(T::DbWeight::get().reads(28))
			.saturating_add(T::DbWeight::get().writes(24))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: Presto Managers (r:1 w:1)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	fn add_presto_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3697`
		// Minimum execution time: 6_617 nanoseconds.
		Weight::from_parts(7_100_000, 3697)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: Presto Managers (r:1 w:1)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	fn remove_presto_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `167`
		//  Estimated: `3697`
		// Minimum execution time: 7_713 nanoseconds.
		Weight::from_parts(8_696_000, 3697)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: Presto Auditors (r:1 w:1)
	/// Proof: Presto Auditors (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	fn add_presto_auditor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3697`
		// Minimum execution time: 6_256 nanoseconds.
		Weight::from_parts(6_909_000, 3697)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: Presto Auditors (r:1 w:1)
	/// Proof: Presto Auditors (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	fn remove_presto_auditor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `167`
		//  Estimated: `3697`
		// Minimum execution time: 7_677 nanoseconds.
		Weight::from_parts(8_145_000, 3697)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: Presto Managers (r:1 w:0)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:1 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn mint_presto_usd() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2120`
		//  Estimated: `345198`
		// Minimum execution time: 39_146 nanoseconds.
		Weight::from_parts(41_702_000, 345198)
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: Presto Managers (r:1 w:0)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	fn burn_presto_usd() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1716`
		//  Estimated: `337596`
		// Minimum execution time: 29_891 nanoseconds.
		Weight::from_parts(31_087_000, 337596)
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	/// Storage: Presto Managers (r:1 w:0)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn send_presto_usd() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1838`
		//  Estimated: `343004`
		// Minimum execution time: 37_014 nanoseconds.
		Weight::from_parts(38_331_000, 343004)
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: Presto LastRequestId (r:1 w:1)
	/// Proof: Presto LastRequestId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Presto UserRequests (r:1 w:1)
	/// Proof: Presto UserRequests (max_values: None, max_size: Some(524332), added: 526807, mode: MaxEncodedLen)
	/// Storage: Presto Requests (r:0 w:1)
	/// Proof: Presto Requests (max_values: None, max_size: Some(420), added: 2895, mode: MaxEncodedLen)
	fn create_deposit_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `256`
		//  Estimated: `527813`
		// Minimum execution time: 10_917 nanoseconds.
		Weight::from_parts(11_705_000, 527813)
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: Presto LastRequestId (r:1 w:1)
	/// Proof: Presto LastRequestId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Presto UserRequests (r:1 w:1)
	/// Proof: Presto UserRequests (max_values: None, max_size: Some(524332), added: 526807, mode: MaxEncodedLen)
	/// Storage: Presto Requests (r:0 w:1)
	/// Proof: Presto Requests (max_values: None, max_size: Some(420), added: 2895, mode: MaxEncodedLen)
	fn create_withdraw_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2064`
		//  Estimated: `867346`
		// Minimum execution time: 45_444 nanoseconds.
		Weight::from_parts(47_933_000, 867346)
			.saturating_add(RocksDbWeight::get().reads(9))
			.saturating_add(RocksDbWeight::get().writes(6))
	}
	/// Storage: Presto Requests (r:1 w:1)
	/// Proof: Presto Requests (max_values: None, max_size: Some(420), added: 2895, mode: MaxEncodedLen)
	fn cancel_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `298`
		//  Estimated: `2895`
		// Minimum execution time: 8_267 nanoseconds.
		Weight::from_parts(8_626_000, 2895)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: Presto Managers (r:1 w:0)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	/// Storage: Presto Requests (r:1 w:1)
	/// Proof: Presto Requests (max_values: None, max_size: Some(420), added: 2895, mode: MaxEncodedLen)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	fn approve_deposit_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2236`
		//  Estimated: `346800`
		// Minimum execution time: 45_051 nanoseconds.
		Weight::from_parts(47_826_000, 346800)
			.saturating_add(RocksDbWeight::get().reads(9))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: Presto Managers (r:1 w:0)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	/// Storage: Presto Requests (r:1 w:1)
	/// Proof: Presto Requests (max_values: None, max_size: Some(420), added: 2895, mode: MaxEncodedLen)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	fn approve_withdraw_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2359`
		//  Estimated: `344320`
		// Minimum execution time: 42_741 nanoseconds.
		Weight::from_parts(44_619_000, 344320)
			.saturating_add(RocksDbWeight::get().reads(8))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: Presto Managers (r:1 w:0)
	/// Proof: Presto Managers (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	/// Storage: Presto Requests (r:1 w:1)
	/// Proof: Presto Requests (max_values: None, max_size: Some(420), added: 2895, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	fn decline_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `565`
		//  Estimated: `7095`
		// Minimum execution time: 11_711 nanoseconds.
		Weight::from_parts(12_575_000, 7095)
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: Presto LastCropReceiptId (r:1 w:1)
	/// Proof: Presto LastCropReceiptId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Presto UserCropReceipts (r:1 w:1)
	/// Proof: Presto UserCropReceipts (max_values: None, max_size: Some(524332), added: 526807, mode: MaxEncodedLen)
	/// Storage: Presto CropReceiptsContent (r:0 w:1)
	/// Proof: Presto CropReceiptsContent (max_values: None, max_size: Some(30740), added: 33215, mode: MaxEncodedLen)
	/// Storage: Presto CropReceipts (r:0 w:1)
	/// Proof: Presto CropReceipts (max_values: None, max_size: Some(398), added: 2873, mode: MaxEncodedLen)
	fn create_crop_receipt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `256`
		//  Estimated: `527813`
		// Minimum execution time: 15_160 nanoseconds.
		Weight::from_parts(16_304_000, 527813)
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: Presto Auditors (r:1 w:0)
	/// Proof: Presto Auditors (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
	/// Storage: Presto CropReceipts (r:1 w:1)
	/// Proof: Presto CropReceipts (max_values: None, max_size: Some(398), added: 2873, mode: MaxEncodedLen)
	fn rate_crop_receipt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `429`
		//  Estimated: `6570`
		// Minimum execution time: 10_366 nanoseconds.
		Weight::from_parts(11_125_000, 6570)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: Presto CropReceipts (r:1 w:1)
	/// Proof: Presto CropReceipts (max_values: None, max_size: Some(398), added: 2873, mode: MaxEncodedLen)
	fn decline_crop_receipt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `408`
		//  Estimated: `2873`
		// Minimum execution time: 8_628 nanoseconds.
		Weight::from_parts(9_092_000, 2873)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: Presto CropReceipts (r:1 w:1)
	/// Proof: Presto CropReceipts (max_values: None, max_size: Some(398), added: 2873, mode: MaxEncodedLen)
	/// Storage: Presto LastCouponId (r:1 w:1)
	/// Proof: Presto LastCouponId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: System Account (r:3 w:3)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Assets AssetOwners (r:2 w:1)
	/// Proof Skipped: Assets AssetOwners (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Owners (r:2 w:2)
	/// Proof Skipped: Permissions Owners (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:3 w:1)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:3 w:3)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: DEXManager DEXInfos (r:1 w:0)
	/// Proof Skipped: DEXManager DEXInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: TradingPair EnabledSources (r:1 w:1)
	/// Proof Skipped: TradingPair EnabledSources (max_values: None, max_size: None, mode: Measured)
	/// Storage: OrderBook OrderBooks (r:1 w:1)
	/// Proof: OrderBook OrderBooks (max_values: None, max_size: Some(238), added: 2713, mode: MaxEncodedLen)
	/// Storage: Technical TechAccounts (r:1 w:1)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: OrderBook UserLimitOrders (r:1 w:1)
	/// Proof: OrderBook UserLimitOrders (max_values: None, max_size: Some(16518), added: 18993, mode: MaxEncodedLen)
	/// Storage: OrderBook Asks (r:1 w:1)
	/// Proof: OrderBook Asks (max_values: None, max_size: Some(16503), added: 18978, mode: MaxEncodedLen)
	/// Storage: OrderBook AggregatedAsks (r:1 w:1)
	/// Proof: OrderBook AggregatedAsks (max_values: None, max_size: Some(34902), added: 37377, mode: MaxEncodedLen)
	/// Storage: OrderBook AggregatedBids (r:1 w:0)
	/// Proof: OrderBook AggregatedBids (max_values: None, max_size: Some(34902), added: 37377, mode: MaxEncodedLen)
	/// Storage: OrderBook LimitOrders (r:1 w:1)
	/// Proof: OrderBook LimitOrders (max_values: None, max_size: Some(236), added: 2711, mode: MaxEncodedLen)
	/// Storage: OrderBook ExpirationsAgenda (r:1 w:1)
	/// Proof: OrderBook ExpirationsAgenda (max_values: None, max_size: Some(86022), added: 88497, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:0 w:1)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfos (r:0 w:1)
	/// Proof Skipped: Assets AssetInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: Presto Coupons (r:0 w:1)
	/// Proof: Presto Coupons (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	fn publish_crop_receipt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5096`
		//  Estimated: `618782`
		// Minimum execution time: 217_008 nanoseconds.
		Weight::from_parts(226_387_000, 618782)
			.saturating_add(RocksDbWeight::get().reads(28))
			.saturating_add(RocksDbWeight::get().writes(24))
	}
}
