[package]
edition = "2021"
name = "xst-benchmarking"
version = "0.1.0"
authors = ["Polka Biome Ltd. <jihoon@tutanota.de>"]
license = "BSD-4-Clause"
homepage = "https://sora.org"
repository = "https://github.com/sora-xor/sora2-network"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false }
currencies = { workspace = true }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
hex-literal = { version = "0.4.1" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
common = { path = "../../../common", default-features = false }
permissions = { path = "../../permissions", default-features = false }
dex-manager = { path = "../../dex-manager", default-features = false }
mock-liquidity-source = { path = "../../mock-liquidity-source", default-features = false }
technical = { path = "../../technical", default-features = false }
trading-pair = { path = "../../trading-pair", default-features = false }
band = { path = "../../band", default-features = false }
oracle-proxy = { path = "../../oracle-proxy", default-features = false }
xst = { path = "../../xst", default-features = false }
assets = { path = "../../assets", default-features = false }
scale-info = { version = "2", default-features = false }
tokens = { workspace = true }
price-tools = { path = "../../price-tools", default-features = false }

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
tokens = { workspace = true }
dex-api = { path = "../../dex-api", default-features = false }
pool-xyk = { path = "../../pool-xyk", default-features = false }
pswap-distribution = { path = "../../pswap-distribution", default-features = false }
demeter-farming-platform = { path = "../../demeter-farming-platform", default-features = false }
ceres-liquidity-locker = { path = "../../ceres-liquidity-locker", default-features = false }
common = { path = "../../../common", default-features = false, features = [
    "test",
] }

[features]
default = ["std"]
std = [
    'codec/std',
    "currencies/std",
    "frame-support/std",
    "frame-system/std",
    "frame-benchmarking/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "common/std",
    "permissions/std",
    "dex-manager/std",
    "mock-liquidity-source/std",
    "technical/std",
    "trading-pair/std",
    "band/std",
    "oracle-proxy/std",
    "xst/std",
    "assets/std",
    "scale-info/std",
    "tokens/std",
    "price-tools/std",
]

runtime-benchmarks = [
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
]
