// This file is part of HydraDX.

// Copyright (C) 2020-2024  Intergalactic, Limited (GIB).
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_polkamarket`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-02-10, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `williams-macbook-pro-2.home`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("/tmp/hydradx-dev-bench.json")`, DB CACHE: `1024`

// Executed Command:
// target/release/hydradx
// benchmark
// pallet
// --chain
// /tmp/hydradx-dev-bench.json
// --pallet
// pallet_polkamarket
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --template
// scripts/pallet-weight-template.hbs
// --output
// /Users/williamrichter/Git/polkamarket/pallets/polkamarket/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::*;

/// Weights for `pallet_polkamarket`.
pub struct SubstrateWeight<T>(PhantomData<T>);

/// Weights for `pallet_polkamarket` using the HydraDX node and recommended hardware.
pub struct HydraWeight<T>(PhantomData<T>);
impl<T: frame_system::Config + pallet::Config> crate::WeightInfo for HydraWeight<T> {
	/// Storage: `Polkamarket::NextConditionId` (r:1 w:1)
	/// Proof: `Polkamarket::NextConditionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarket::Conditions` (r:0 w:1)
	/// Proof: `Polkamarket::Conditions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_condition() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `1627`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 1627)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Polkamarket::Conditions` (r:1 w:0)
	/// Proof: `Polkamarket::Conditions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarket::NextMarketId` (r:1 w:1)
	/// Proof: `Polkamarket::NextMarketId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarket::MarketCollateral` (r:0 w:1)
	/// Proof: `Polkamarket::MarketCollateral` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarket::Markets` (r:0 w:1)
	/// Proof: `Polkamarket::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_market(routed_transfers: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `242`
		//  Estimated: `3707`
		// Minimum execution time: 16_000_000 picoseconds.
		let base = Weight::from_parts(17_000_000, 3707)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64));
		let per_transfer = T::CollateralRouterWeight::get();
		base.saturating_add(per_transfer.saturating_mul(routed_transfers.into()))
	}
	/// Storage: `Polkamarket::Markets` (r:1 w:0)
	/// Proof: `Polkamarket::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarket::Commitments` (r:1 w:1)
	/// Proof: `Polkamarket::Commitments` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn commit_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `317`
		//  Estimated: `3782`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 3782)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Polkamarket::Markets` (r:1 w:0)
	/// Proof: `Polkamarket::Markets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarket::Commitments` (r:1 w:1)
	/// Proof: `Polkamarket::Commitments` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarket::MarketOpenInterest` (r:1 w:1)
	/// Proof: `Polkamarket::MarketOpenInterest` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Polkamarket::CreatorRewardActivated` (r:1 w:0)
	/// Proof: `Polkamarket::CreatorRewardActivated` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn reveal_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `3914`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(25_000_000, 3914)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn set_bridge_wallet() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn bridge_deposit() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn bridge_withdraw() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

impl<T: frame_system::Config + pallet::Config> crate::WeightInfo for SubstrateWeight<T> {
	fn create_condition() -> Weight {
		Weight::from_parts(10_000_000, 1627)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn create_market(routed_transfers: u32) -> Weight {
		let base = Weight::from_parts(17_000_000, 3707)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64));
		let per_transfer = T::CollateralRouterWeight::get();
		base.saturating_add(per_transfer.saturating_mul(routed_transfers.into()))
	}
	fn commit_order() -> Weight {
		Weight::from_parts(16_000_000, 3782)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn reveal_order() -> Weight {
		Weight::from_parts(25_000_000, 3914)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn set_bridge_wallet() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn bridge_deposit() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn bridge_withdraw() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

impl crate::WeightInfo for () {
	fn create_condition() -> Weight {
		Weight::from_parts(10_000_000, 1627)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn create_market(routed_transfers: u32) -> Weight {
		let base = Weight::from_parts(17_000_000, 3707)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64));
		let per_transfer = Weight::from_parts(8_000_000, 1024);
		base.saturating_add(per_transfer.saturating_mul(routed_transfers.into()))
	}
	fn commit_order() -> Weight {
		Weight::from_parts(16_000_000, 3782)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn reveal_order() -> Weight {
		Weight::from_parts(25_000_000, 3914)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn set_bridge_wallet() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn bridge_deposit() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn bridge_withdraw() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
