// This file is part of the SORA network and Polkaswap app.

// Copyright (c) 2020, 2021, Polka Biome Ltd. All rights reserved.
// SPDX-License-Identifier: BSD-4-Clause

// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:

// Redistributions of source code must retain the above copyright notice, this list
// of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice, this
// list of conditions and the following disclaimer in the documentation and/or other
// materials provided with the distribution.
//
// All advertising materials mentioning features or use of this software must display
// the following acknowledgement: This product includes software developed by Polka Biome
// Ltd., SORA, and Polkaswap.
//
// Neither the name of the Polka Biome Ltd. nor the names of its contributors may be used
// to endorse or promote products derived from this software without specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY Polka Biome Ltd. AS IS AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Polka Biome Ltd. BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
// USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

//! Autogenerated weights for sccp
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-02-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `takemiyacStudio.lan`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("local"), DB CACHE: 1024

// Executed Command:
// ./target/release/framenode
// benchmark
// pallet
// --chain=local
// --steps=50
// --repeat=20
// --pallet=sccp
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --header=./misc/file_header.txt
// --template=./misc/pallet-weight-template.hbs
// --output=./pallets/sccp/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for sccp.
pub trait WeightInfo {
	fn add_token() -> Weight;
	fn set_remote_token() -> Weight;
	fn set_domain_endpoint() -> Weight;
	fn clear_domain_endpoint() -> Weight;
	fn init_bsc_light_client(a: u32, ) -> Weight;
	fn submit_bsc_header(a: u32, ) -> Weight;
	fn set_bsc_validators(a: u32, ) -> Weight;
	fn init_tron_light_client(a: u32, ) -> Weight;
	fn submit_tron_header(a: u32, ) -> Weight;
	fn set_tron_witnesses(a: u32, ) -> Weight;
	fn set_solana_vote_authorities(a: u32, ) -> Weight;
	fn clear_solana_vote_authorities() -> Weight;
	fn activate_token() -> Weight;
	fn pause_token() -> Weight;
	fn resume_token() -> Weight;
	fn remove_token() -> Weight;
	fn finalize_remove() -> Weight;
	fn set_inbound_grace_period() -> Weight;
	fn set_required_domains(a: u32, ) -> Weight;
	fn set_inbound_finality_mode() -> Weight;
	fn set_inbound_domain_paused() -> Weight;
	fn set_outbound_domain_paused() -> Weight;
	fn invalidate_inbound_message() -> Weight;
	fn clear_invalidated_inbound_message() -> Weight;
	fn burn() -> Weight;
	fn mint_from_proof() -> Weight;
	fn attest_burn() -> Weight;
}

/// Weights for sccp using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Sccp Tokens (r:1 w:1)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetOwners (r:1 w:0)
	/// Proof Skipped: Assets AssetOwners (max_values: None, max_size: None, mode: Measured)
	/// Storage: EthBridge NextNetworkId (r:1 w:0)
	/// Proof Skipped: EthBridge NextNetworkId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: EthBridge RegisteredAsset (r:1 w:0)
	/// Proof Skipped: EthBridge RegisteredAsset (max_values: None, max_size: None, mode: Measured)
	/// Storage: EthBridge RequestsQueue (r:1 w:0)
	/// Proof Skipped: EthBridge RequestsQueue (max_values: None, max_size: None, mode: Measured)
	/// Storage: JettonApp TokenAddresses (r:1 w:0)
	/// Proof Skipped: JettonApp TokenAddresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:1 w:1)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Permissions Permissions (r:3 w:1)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Owners (r:2 w:2)
	/// Proof Skipped: Permissions Owners (max_values: None, max_size: None, mode: Measured)
	fn add_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4133`
		//  Estimated: `74128`
		// Minimum execution time: 79_000_000 picoseconds.
		Weight::from_parts(81_000_000, 74128)
			.saturating_add(T::DbWeight::get().reads(14_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: Sccp Tokens (r:1 w:0)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp RemoteToken (r:0 w:1)
	/// Proof Skipped: Sccp RemoteToken (max_values: None, max_size: None, mode: Measured)
	fn set_remote_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `190`
		//  Estimated: `2855`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(12_000_000, 2855)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp DomainEndpoint (r:0 w:1)
	/// Proof Skipped: Sccp DomainEndpoint (max_values: None, max_size: None, mode: Measured)
	fn set_domain_endpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp DomainEndpoint (r:0 w:1)
	/// Proof Skipped: Sccp DomainEndpoint (max_values: None, max_size: None, mode: Measured)
	fn clear_domain_endpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp BscHead (r:0 w:1)
	/// Proof Skipped: Sccp BscHead (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscFinalized (r:0 w:1)
	/// Proof Skipped: Sccp BscFinalized (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscRecentsLowerBound (r:0 w:1)
	/// Proof Skipped: Sccp BscRecentsLowerBound (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscValidators (r:0 w:1)
	/// Proof Skipped: Sccp BscValidators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscParams (r:0 w:1)
	/// Proof Skipped: Sccp BscParams (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscHeadersByNumber (r:0 w:1)
	/// Proof Skipped: Sccp BscHeadersByNumber (max_values: None, max_size: None, mode: Measured)
	/// The range of component `a` is `[1, 2]`.
	fn init_bsc_light_client(_a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `116`
		//  Estimated: `696`
		// Minimum execution time: 51_000_000 picoseconds.
		Weight::from_parts(61_844_897, 696)
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: Sccp BscParams (r:1 w:0)
	/// Proof Skipped: Sccp BscParams (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscValidators (r:1 w:0)
	/// Proof Skipped: Sccp BscValidators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscHead (r:1 w:0)
	/// Proof Skipped: Sccp BscHead (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `a` is `[1, 2]`.
	fn submit_bsc_header(_a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `415`
		//  Estimated: `2730`
		// Minimum execution time: 40_000_000 picoseconds.
		// Conservative floor: benchmark setup for this path can under-exercise full header import.
		Weight::from_parts(300_000_000, 2730)
			.saturating_add(T::DbWeight::get().reads(3_u64))
	}
	/// Storage: Sccp BscHead (r:1 w:0)
	/// Proof Skipped: Sccp BscHead (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscValidators (r:0 w:1)
	/// Proof Skipped: Sccp BscValidators (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `a` is `[1, 64]`.
	fn set_bsc_validators(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `116`
		//  Estimated: `727`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_225_629, 727)
			// Standard Error: 1_595
			.saturating_add(Weight::from_parts(193_527, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// The range of component `a` is `[1, 2]`.
	fn init_tron_light_client(_a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_000_000 picoseconds.
		// Conservative floor: benchmark setup uses synthetic TRON data.
		Weight::from_parts(200_000_000, 0)
	}
	/// Storage: Sccp TronParams (r:1 w:0)
	/// Proof Skipped: Sccp TronParams (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `a` is `[1, 2]`.
	fn submit_tron_header(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `116`
		//  Estimated: `611`
		// Minimum execution time: 4_000_000 picoseconds.
		// Conservative floor: benchmark setup uses synthetic TRON data.
		Weight::from_parts(300_000_000, 611)
			// Standard Error: 159_415
			.saturating_add(Weight::from_parts(287_755, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: Sccp TronParams (r:1 w:0)
	/// Proof Skipped: Sccp TronParams (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp TronHead (r:1 w:0)
	/// Proof Skipped: Sccp TronHead (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp TronWitnesses (r:0 w:1)
	/// Proof Skipped: Sccp TronWitnesses (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `a` is `[1, 64]`.
	fn set_tron_witnesses(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `116`
		//  Estimated: `1338`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(9_697_429, 1338)
			// Standard Error: 2_283
			.saturating_add(Weight::from_parts(195_466, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp InboundAttesterThreshold (r:0 w:1)
	/// Proof Skipped: Sccp InboundAttesterThreshold (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp InboundAttesters (r:0 w:1)
	/// Proof Skipped: Sccp InboundAttesters (max_values: None, max_size: None, mode: Measured)
	/// The range of component `a` is `[1, 64]`.
	fn set_solana_vote_authorities(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_593_723, 0)
			// Standard Error: 1_805
			.saturating_add(Weight::from_parts(188_724, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Sccp InboundAttesterThreshold (r:0 w:1)
	/// Proof Skipped: Sccp InboundAttesterThreshold (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp InboundAttesters (r:0 w:1)
	/// Proof Skipped: Sccp InboundAttesters (max_values: None, max_size: None, mode: Measured)
	fn clear_solana_vote_authorities() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Sccp Tokens (r:1 w:1)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp RequiredDomains (r:1 w:0)
	/// Proof Skipped: Sccp RequiredDomains (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp RemoteToken (r:5 w:0)
	/// Proof Skipped: Sccp RemoteToken (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp DomainEndpoint (r:5 w:0)
	/// Proof Skipped: Sccp DomainEndpoint (max_values: None, max_size: None, mode: Measured)
	fn activate_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `956`
		//  Estimated: `31544`
		// Minimum execution time: 51_000_000 picoseconds.
		Weight::from_parts(57_000_000, 31544)
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn pause_token() -> Weight {
		Self::activate_token()
	}
	fn resume_token() -> Weight {
		Self::activate_token()
	}
	/// Storage: Sccp InboundGracePeriod (r:1 w:0)
	/// Proof Skipped: Sccp InboundGracePeriod (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp Tokens (r:1 w:1)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	fn remove_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `260`
		//  Estimated: `3490`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(13_000_000, 3490)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp Tokens (r:1 w:1)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp RemoteToken (r:0 w:5)
	/// Proof Skipped: Sccp RemoteToken (max_values: None, max_size: None, mode: Measured)
	fn finalize_remove() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `551`
		//  Estimated: `3577`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(20_000_000, 3577)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: Sccp InboundGracePeriod (r:0 w:1)
	/// Proof Skipped: Sccp InboundGracePeriod (max_values: Some(1), max_size: None, mode: Measured)
	fn set_inbound_grace_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp RequiredDomains (r:0 w:1)
	/// Proof Skipped: Sccp RequiredDomains (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `a` is `[5, 6]`.
	fn set_required_domains(_a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_836_734, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp InboundFinalityModes (r:0 w:1)
	/// Proof Skipped: Sccp InboundFinalityModes (max_values: None, max_size: None, mode: Measured)
	fn set_inbound_finality_mode() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp InboundDomainPaused (r:0 w:1)
	/// Proof Skipped: Sccp InboundDomainPaused (max_values: None, max_size: None, mode: Measured)
	fn set_inbound_domain_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp OutboundDomainPaused (r:0 w:1)
	/// Proof Skipped: Sccp OutboundDomainPaused (max_values: None, max_size: None, mode: Measured)
	fn set_outbound_domain_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp InvalidatedInbound (r:0 w:1)
	/// Proof Skipped: Sccp InvalidatedInbound (max_values: None, max_size: None, mode: Measured)
	fn invalidate_inbound_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp InvalidatedInbound (r:0 w:1)
	/// Proof Skipped: Sccp InvalidatedInbound (max_values: None, max_size: None, mode: Measured)
	fn clear_invalidated_inbound_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp OutboundDomainPaused (r:1 w:0)
	/// Proof Skipped: Sccp OutboundDomainPaused (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp DomainEndpoint (r:1 w:0)
	/// Proof Skipped: Sccp DomainEndpoint (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp Tokens (r:1 w:0)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp RemoteToken (r:1 w:0)
	/// Proof Skipped: Sccp RemoteToken (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp Nonce (r:1 w:1)
	/// Proof Skipped: Sccp Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp Burns (r:1 w:1)
	/// Proof Skipped: Sccp Burns (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:1 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:1 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	/// Storage: LeafProvider LatestDigest (r:1 w:1)
	/// Proof Skipped: LeafProvider LatestDigest (max_values: Some(1), max_size: None, mode: Measured)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3392`
		//  Estimated: `384418`
		// Minimum execution time: 65_000_000 picoseconds.
		Weight::from_parts(69_000_000, 384418)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: Sccp DomainEndpoint (r:1 w:0)
	/// Proof Skipped: Sccp DomainEndpoint (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp InboundFinalityModes (r:1 w:0)
	/// Proof Skipped: Sccp InboundFinalityModes (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp InboundDomainPaused (r:1 w:0)
	/// Proof Skipped: Sccp InboundDomainPaused (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp RemoteToken (r:1 w:0)
	/// Proof Skipped: Sccp RemoteToken (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp Tokens (r:1 w:0)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp InvalidatedInbound (r:1 w:0)
	/// Proof Skipped: Sccp InvalidatedInbound (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp ProcessedInbound (r:1 w:0)
	/// Proof Skipped: Sccp ProcessedInbound (max_values: None, max_size: None, mode: Measured)
	fn mint_from_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `878`
		//  Estimated: `30177`
		// Minimum execution time: 30_000_000 picoseconds.
		// Conservative floor: benchmark setup currently exercises a lightweight proof path.
		Weight::from_parts(150_000_000, 30177)
			.saturating_add(T::DbWeight::get().reads(9_u64))
	}
	/// Storage: Sccp InboundDomainPaused (r:1 w:0)
	/// Proof Skipped: Sccp InboundDomainPaused (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp OutboundDomainPaused (r:1 w:0)
	/// Proof Skipped: Sccp OutboundDomainPaused (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp DomainEndpoint (r:1 w:0)
	/// Proof Skipped: Sccp DomainEndpoint (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp InboundFinalityModes (r:1 w:0)
	/// Proof Skipped: Sccp InboundFinalityModes (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp Tokens (r:1 w:0)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp RemoteToken (r:2 w:0)
	/// Proof Skipped: Sccp RemoteToken (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp InvalidatedInbound (r:1 w:0)
	/// Proof Skipped: Sccp InvalidatedInbound (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp AttestedOutbound (r:1 w:0)
	/// Proof Skipped: Sccp AttestedOutbound (max_values: None, max_size: None, mode: Measured)
	fn attest_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `900`
		//  Estimated: `36225`
		// Minimum execution time: 34_000_000 picoseconds.
		// Conservative floor: benchmark setup currently exercises a lightweight proof path.
		Weight::from_parts(150_000_000, 36225)
			.saturating_add(T::DbWeight::get().reads(11_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: Sccp Tokens (r:1 w:1)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetOwners (r:1 w:0)
	/// Proof Skipped: Assets AssetOwners (max_values: None, max_size: None, mode: Measured)
	/// Storage: EthBridge NextNetworkId (r:1 w:0)
	/// Proof Skipped: EthBridge NextNetworkId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: EthBridge RegisteredAsset (r:1 w:0)
	/// Proof Skipped: EthBridge RegisteredAsset (max_values: None, max_size: None, mode: Measured)
	/// Storage: EthBridge RequestsQueue (r:1 w:0)
	/// Proof Skipped: EthBridge RequestsQueue (max_values: None, max_size: None, mode: Measured)
	/// Storage: JettonApp TokenAddresses (r:1 w:0)
	/// Proof Skipped: JettonApp TokenAddresses (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:1 w:1)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Permissions Permissions (r:3 w:1)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Owners (r:2 w:2)
	/// Proof Skipped: Permissions Owners (max_values: None, max_size: None, mode: Measured)
	fn add_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4133`
		//  Estimated: `74128`
		// Minimum execution time: 79_000_000 picoseconds.
		Weight::from_parts(81_000_000, 74128)
			.saturating_add(RocksDbWeight::get().reads(14_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: Sccp Tokens (r:1 w:0)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp RemoteToken (r:0 w:1)
	/// Proof Skipped: Sccp RemoteToken (max_values: None, max_size: None, mode: Measured)
	fn set_remote_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `190`
		//  Estimated: `2855`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(12_000_000, 2855)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp DomainEndpoint (r:0 w:1)
	/// Proof Skipped: Sccp DomainEndpoint (max_values: None, max_size: None, mode: Measured)
	fn set_domain_endpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp DomainEndpoint (r:0 w:1)
	/// Proof Skipped: Sccp DomainEndpoint (max_values: None, max_size: None, mode: Measured)
	fn clear_domain_endpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp BscHead (r:0 w:1)
	/// Proof Skipped: Sccp BscHead (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscFinalized (r:0 w:1)
	/// Proof Skipped: Sccp BscFinalized (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscRecentsLowerBound (r:0 w:1)
	/// Proof Skipped: Sccp BscRecentsLowerBound (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscValidators (r:0 w:1)
	/// Proof Skipped: Sccp BscValidators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscParams (r:0 w:1)
	/// Proof Skipped: Sccp BscParams (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscHeadersByNumber (r:0 w:1)
	/// Proof Skipped: Sccp BscHeadersByNumber (max_values: None, max_size: None, mode: Measured)
	/// The range of component `a` is `[1, 2]`.
	fn init_bsc_light_client(_a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `116`
		//  Estimated: `696`
		// Minimum execution time: 51_000_000 picoseconds.
		Weight::from_parts(61_844_897, 696)
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: Sccp BscParams (r:1 w:0)
	/// Proof Skipped: Sccp BscParams (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscValidators (r:1 w:0)
	/// Proof Skipped: Sccp BscValidators (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscHead (r:1 w:0)
	/// Proof Skipped: Sccp BscHead (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `a` is `[1, 2]`.
	fn submit_bsc_header(_a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `415`
		//  Estimated: `2730`
		// Minimum execution time: 40_000_000 picoseconds.
		// Conservative floor: benchmark setup for this path can under-exercise full header import.
		Weight::from_parts(300_000_000, 2730)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
	}
	/// Storage: Sccp BscHead (r:1 w:0)
	/// Proof Skipped: Sccp BscHead (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp BscValidators (r:0 w:1)
	/// Proof Skipped: Sccp BscValidators (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `a` is `[1, 64]`.
	fn set_bsc_validators(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `116`
		//  Estimated: `727`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_225_629, 727)
			// Standard Error: 1_595
			.saturating_add(Weight::from_parts(193_527, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// The range of component `a` is `[1, 2]`.
	fn init_tron_light_client(_a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_000_000 picoseconds.
		// Conservative floor: benchmark setup uses synthetic TRON data.
		Weight::from_parts(200_000_000, 0)
	}
	/// Storage: Sccp TronParams (r:1 w:0)
	/// Proof Skipped: Sccp TronParams (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `a` is `[1, 2]`.
	fn submit_tron_header(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `116`
		//  Estimated: `611`
		// Minimum execution time: 4_000_000 picoseconds.
		// Conservative floor: benchmark setup uses synthetic TRON data.
		Weight::from_parts(300_000_000, 611)
			// Standard Error: 159_415
			.saturating_add(Weight::from_parts(287_755, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: Sccp TronParams (r:1 w:0)
	/// Proof Skipped: Sccp TronParams (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp TronHead (r:1 w:0)
	/// Proof Skipped: Sccp TronHead (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp TronWitnesses (r:0 w:1)
	/// Proof Skipped: Sccp TronWitnesses (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `a` is `[1, 64]`.
	fn set_tron_witnesses(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `116`
		//  Estimated: `1338`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(9_697_429, 1338)
			// Standard Error: 2_283
			.saturating_add(Weight::from_parts(195_466, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp InboundAttesterThreshold (r:0 w:1)
	/// Proof Skipped: Sccp InboundAttesterThreshold (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp InboundAttesters (r:0 w:1)
	/// Proof Skipped: Sccp InboundAttesters (max_values: None, max_size: None, mode: Measured)
	/// The range of component `a` is `[1, 64]`.
	fn set_solana_vote_authorities(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_593_723, 0)
			// Standard Error: 1_805
			.saturating_add(Weight::from_parts(188_724, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Sccp InboundAttesterThreshold (r:0 w:1)
	/// Proof Skipped: Sccp InboundAttesterThreshold (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp InboundAttesters (r:0 w:1)
	/// Proof Skipped: Sccp InboundAttesters (max_values: None, max_size: None, mode: Measured)
	fn clear_solana_vote_authorities() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Sccp Tokens (r:1 w:1)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp RequiredDomains (r:1 w:0)
	/// Proof Skipped: Sccp RequiredDomains (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp RemoteToken (r:5 w:0)
	/// Proof Skipped: Sccp RemoteToken (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp DomainEndpoint (r:5 w:0)
	/// Proof Skipped: Sccp DomainEndpoint (max_values: None, max_size: None, mode: Measured)
	fn activate_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `956`
		//  Estimated: `31544`
		// Minimum execution time: 51_000_000 picoseconds.
		Weight::from_parts(57_000_000, 31544)
			.saturating_add(RocksDbWeight::get().reads(12_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn pause_token() -> Weight {
		Self::activate_token()
	}
	fn resume_token() -> Weight {
		Self::activate_token()
	}
	/// Storage: Sccp InboundGracePeriod (r:1 w:0)
	/// Proof Skipped: Sccp InboundGracePeriod (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp Tokens (r:1 w:1)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	fn remove_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `260`
		//  Estimated: `3490`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(13_000_000, 3490)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp Tokens (r:1 w:1)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp RemoteToken (r:0 w:5)
	/// Proof Skipped: Sccp RemoteToken (max_values: None, max_size: None, mode: Measured)
	fn finalize_remove() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `551`
		//  Estimated: `3577`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(20_000_000, 3577)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: Sccp InboundGracePeriod (r:0 w:1)
	/// Proof Skipped: Sccp InboundGracePeriod (max_values: Some(1), max_size: None, mode: Measured)
	fn set_inbound_grace_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp RequiredDomains (r:0 w:1)
	/// Proof Skipped: Sccp RequiredDomains (max_values: Some(1), max_size: None, mode: Measured)
	/// The range of component `a` is `[5, 6]`.
	fn set_required_domains(_a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_836_734, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp InboundFinalityModes (r:0 w:1)
	/// Proof Skipped: Sccp InboundFinalityModes (max_values: None, max_size: None, mode: Measured)
	fn set_inbound_finality_mode() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp InboundDomainPaused (r:0 w:1)
	/// Proof Skipped: Sccp InboundDomainPaused (max_values: None, max_size: None, mode: Measured)
	fn set_inbound_domain_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp OutboundDomainPaused (r:0 w:1)
	/// Proof Skipped: Sccp OutboundDomainPaused (max_values: None, max_size: None, mode: Measured)
	fn set_outbound_domain_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp InvalidatedInbound (r:0 w:1)
	/// Proof Skipped: Sccp InvalidatedInbound (max_values: None, max_size: None, mode: Measured)
	fn invalidate_inbound_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp InvalidatedInbound (r:0 w:1)
	/// Proof Skipped: Sccp InvalidatedInbound (max_values: None, max_size: None, mode: Measured)
	fn clear_invalidated_inbound_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Sccp OutboundDomainPaused (r:1 w:0)
	/// Proof Skipped: Sccp OutboundDomainPaused (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp DomainEndpoint (r:1 w:0)
	/// Proof Skipped: Sccp DomainEndpoint (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp Tokens (r:1 w:0)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp RemoteToken (r:1 w:0)
	/// Proof Skipped: Sccp RemoteToken (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp Nonce (r:1 w:1)
	/// Proof Skipped: Sccp Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Sccp Burns (r:1 w:1)
	/// Proof Skipped: Sccp Burns (max_values: None, max_size: None, mode: Measured)
	/// Storage: Technical TechAccounts (r:1 w:0)
	/// Proof Skipped: Technical TechAccounts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Permissions Permissions (r:1 w:0)
	/// Proof Skipped: Permissions Permissions (max_values: None, max_size: None, mode: Measured)
	/// Storage: ExtendedAssets SoulboundAsset (r:1 w:0)
	/// Proof: ExtendedAssets SoulboundAsset (max_values: None, max_size: Some(322091), added: 324566, mode: MaxEncodedLen)
	/// Storage: Assets AssetInfosV2 (r:1 w:0)
	/// Proof Skipped: Assets AssetInfosV2 (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(136), added: 2611, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(56), added: 2531, mode: MaxEncodedLen)
	/// Storage: LeafProvider LatestDigest (r:1 w:1)
	/// Proof Skipped: LeafProvider LatestDigest (max_values: Some(1), max_size: None, mode: Measured)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3392`
		//  Estimated: `384418`
		// Minimum execution time: 65_000_000 picoseconds.
		Weight::from_parts(69_000_000, 384418)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: Sccp DomainEndpoint (r:1 w:0)
	/// Proof Skipped: Sccp DomainEndpoint (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp InboundFinalityModes (r:1 w:0)
	/// Proof Skipped: Sccp InboundFinalityModes (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp InboundDomainPaused (r:1 w:0)
	/// Proof Skipped: Sccp InboundDomainPaused (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp RemoteToken (r:1 w:0)
	/// Proof Skipped: Sccp RemoteToken (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp Tokens (r:1 w:0)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp InvalidatedInbound (r:1 w:0)
	/// Proof Skipped: Sccp InvalidatedInbound (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp ProcessedInbound (r:1 w:0)
	/// Proof Skipped: Sccp ProcessedInbound (max_values: None, max_size: None, mode: Measured)
	fn mint_from_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `878`
		//  Estimated: `30177`
		// Minimum execution time: 30_000_000 picoseconds.
		// Conservative floor: benchmark setup currently exercises a lightweight proof path.
		Weight::from_parts(150_000_000, 30177)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
	}
	/// Storage: Sccp InboundDomainPaused (r:1 w:0)
	/// Proof Skipped: Sccp InboundDomainPaused (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp OutboundDomainPaused (r:1 w:0)
	/// Proof Skipped: Sccp OutboundDomainPaused (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp DomainEndpoint (r:1 w:0)
	/// Proof Skipped: Sccp DomainEndpoint (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp InboundFinalityModes (r:1 w:0)
	/// Proof Skipped: Sccp InboundFinalityModes (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp Tokens (r:1 w:0)
	/// Proof Skipped: Sccp Tokens (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp RemoteToken (r:2 w:0)
	/// Proof Skipped: Sccp RemoteToken (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp InvalidatedInbound (r:1 w:0)
	/// Proof Skipped: Sccp InvalidatedInbound (max_values: None, max_size: None, mode: Measured)
	/// Storage: Sccp AttestedOutbound (r:1 w:0)
	/// Proof Skipped: Sccp AttestedOutbound (max_values: None, max_size: None, mode: Measured)
	fn attest_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `900`
		//  Estimated: `36225`
		// Minimum execution time: 34_000_000 picoseconds.
		// Conservative floor: benchmark setup currently exercises a lightweight proof path.
		Weight::from_parts(150_000_000, 36225)
			.saturating_add(RocksDbWeight::get().reads(11_u64))
	}
}
