// This file is part of the SORA network and Polkaswap app.

// Copyright (c) 2020, 2021, Polka Biome Ltd. All rights reserved.
// SPDX-License-Identifier: BSD-4-Clause

// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:

// Redistributions of source code must retain the above copyright notice, this list
// of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice, this
// list of conditions and the following disclaimer in the documentation and/or other
// materials provided with the distribution.
//
// All advertising materials mentioning features or use of this software must display
// the following acknowledgement: This product includes software developed by Polka Biome
// Ltd., SORA, and Polkaswap.
//
// Neither the name of the Polka Biome Ltd. nor the names of its contributors may be used
// to endorse or promote products derived from this software without specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY Polka Biome Ltd. AS IS AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Polka Biome Ltd. BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
// USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

//! Autogenerated weights for `xst`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-03-29, STEPS: `10`, REPEAT: 2, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `MacBook-Pro-qwerty.local`, CPU: `<UNKNOWN>`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/debug/framenode
// benchmark
// pallet
// --chain=dev
// --pallet
// xst
// --extrinsic
// *
// --steps
// 10
// --repeat
// 2
// --output
// pallets/xst/src/weigths_raw.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;
use common::weights::constants::EXTRINSIC_FIXED_WEIGHT;

/// Weight functions for `xst`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
    // Storage: XSTPool ReferenceAssetId (r:0 w:1)
    fn set_reference_asset() -> Weight {
        (99_000_000 as Weight)
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    // Storage: XSTPool EnabledSymbols (r:1 w:1)
    // Storage: OracleProxy EnabledOracles (r:1 w:0)
    // Storage: Band SymbolRates (r:2 w:0)
    // Storage: Assets AssetOwners (r:1 w:0)
    // Storage: DEXManager DEXInfos (r:1 w:0)
    // Storage: TradingPair EnabledSources (r:1 w:0)
    // Storage: XSTPool EnabledSynthetics (r:0 w:1)
    fn enable_synthetic_asset() -> Weight {
        (339_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(7 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    // Storage: XSTPool EnabledSynthetics (r:1 w:1)
    // Storage: XSTPool EnabledSymbols (r:0 w:1)
    fn disable_synthetic_asset() -> Weight {
        (157_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    // Storage: XSTPool PermissionedTechAccount (r:1 w:0)
    // Storage: Assets AssetOwners (r:1 w:1)
    // Storage: System Account (r:1 w:1)
    // Storage: Permissions Owners (r:2 w:2)
    // Storage: Permissions Permissions (r:3 w:1)
    // Storage: Assets AssetInfos (r:0 w:1)
    fn register_synthetic_asset() -> Weight {
        (689_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(8 as Weight))
            .saturating_add(T::DbWeight::get().writes(6 as Weight))
    }
    // Storage: XSTPool EnabledSynthetics (r:1 w:1)
    fn set_synthetic_asset_fee() -> Weight {
        (134_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    // Storage: XSTPool SyntheticBaseAssetFloorPrice (r:0 w:1)
    fn set_synthetic_base_asset_floor_price() -> Weight {
        (90_000_000 as Weight)
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
}

impl crate::WeightInfo for () {
    fn set_reference_asset() -> Weight {
        EXTRINSIC_FIXED_WEIGHT
    }
    fn enable_synthetic_asset() -> Weight {
        EXTRINSIC_FIXED_WEIGHT
    }
    fn disable_synthetic_asset() -> Weight {
        EXTRINSIC_FIXED_WEIGHT
    }
    fn register_synthetic_asset() -> Weight {
        EXTRINSIC_FIXED_WEIGHT
    }
    fn set_synthetic_asset_fee() -> Weight {
        EXTRINSIC_FIXED_WEIGHT
    }
    fn set_synthetic_base_asset_floor_price() -> Weight {
        EXTRINSIC_FIXED_WEIGHT
    }
}
